package fys;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class Man_LogActivities extends javax.swing.JPanel {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    public Man_LogActivities() {
        initComponents();
        conn = javaconnect.ConnecrDb();

        Manual_Panel.setVisible(false);
        Manual_Panel.setEnabled(false);
        
        //emptyfield_warning.setVisible(false);
        //emptyfield_warning.setEnabled(false);
        
        Update_table();
    }
    
    private void Update_table() {
        try {
            String sql = "SELECT * FROM log";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            Table_Log.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Logo = new javax.swing.JLabel();
        Tab_GraphData = new javax.swing.JLabel();
        Tab_LogActivities = new javax.swing.JLabel();
        Tab_LogOut = new javax.swing.JLabel();
        Label_CallManual = new javax.swing.JLabel();
        Manual_Panel = new javax.swing.JPanel();
        Label_ManualExit = new javax.swing.JLabel();
        Label_Info = new javax.swing.JLabel();
        Label_Title = new javax.swing.JLabel();
        Label_Case = new javax.swing.JLabel();
        Label_Timeframe = new javax.swing.JLabel();
        Box_Case = new javax.swing.JComboBox();
        Box_TimeFrame = new javax.swing.JComboBox();
        Button_Reset = new javax.swing.JLabel();
        Field_Search = new javax.swing.JTextField();
        ScrollPane_Log = new javax.swing.JScrollPane();
        Table_Log = new javax.swing.JTable();
        Background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_LogoMouseClicked(evt);
            }
        });
        add(Label_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 60));

        Tab_GraphData.setBackground(new java.awt.Color(156, 10, 13));
        Tab_GraphData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tab_GraphData.setForeground(new java.awt.Color(255, 255, 255));
        Tab_GraphData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tab_GraphData.setText("Graph Data");
        Tab_GraphData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_GraphData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_GraphData.setOpaque(true);
        Tab_GraphData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_GraphDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab_GraphDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab_GraphDataMouseExited(evt);
            }
        });
        add(Tab_GraphData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, 40));

        Tab_LogActivities.setBackground(new java.awt.Color(255, 255, 255));
        Tab_LogActivities.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tab_LogActivities.setForeground(new java.awt.Color(156, 10, 13));
        Tab_LogActivities.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tab_LogActivities.setText("Log Activities");
        Tab_LogActivities.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_LogActivities.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_LogActivities.setOpaque(true);
        Tab_LogActivities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_LogActivitiesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab_LogActivitiesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab_LogActivitiesMouseExited(evt);
            }
        });
        add(Tab_LogActivities, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 250, 40));

        Tab_LogOut.setBackground(new java.awt.Color(156, 10, 13));
        Tab_LogOut.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tab_LogOut.setForeground(new java.awt.Color(255, 255, 255));
        Tab_LogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tab_LogOut.setText("Log Out");
        Tab_LogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_LogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_LogOut.setOpaque(true);
        Tab_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_LogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab_LogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab_LogOutMouseExited(evt);
            }
        });
        add(Tab_LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 250, 40));

        Label_CallManual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_CallManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_CallManualMouseClicked(evt);
            }
        });
        add(Label_CallManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 50, 50));

        Manual_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Manual_Panel.setEnabled(false);
        Manual_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_ManualExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_ManualExit.setText("X");
        Label_ManualExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_ManualExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_ManualExitMouseClicked(evt);
            }
        });
        Manual_Panel.add(Label_ManualExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 20, 20));

        Label_Info.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_Info.setForeground(new java.awt.Color(153, 0, 0));
        Label_Info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Info.setText("<html>\nSelect the timeframe and type of case by\nusing their respective drop down buttons.\nThis will generate a table of data based on your\nchoices. You can also search through the data using\nthe search bar located above the table.");
        Label_Info.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Manual_Panel.add(Label_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 420));

        Label_Title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Title.setForeground(new java.awt.Color(156, 10, 13));
        Label_Title.setText("Manual");
        Manual_Panel.add(Label_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));

        add(Manual_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 290, 590));

        Label_Case.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_Case.setForeground(new java.awt.Color(156, 10, 13));
        Label_Case.setText("Case:");
        add(Label_Case, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 40));

        Label_Timeframe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_Timeframe.setForeground(new java.awt.Color(156, 10, 13));
        Label_Timeframe.setText("Timeframe:");
        add(Label_Timeframe, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 30));

        Box_Case.setForeground(new java.awt.Color(156, 10, 13));
        Box_Case.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Unresolved", "Resolved", "Permanently lost" }));
        add(Box_Case, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 120, 20));

        Box_TimeFrame.setForeground(new java.awt.Color(156, 10, 13));
        Box_TimeFrame.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Today", "This week", "This Month", "This Year" }));
        Box_TimeFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_TimeFrameActionPerformed(evt);
            }
        });
        add(Box_TimeFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 120, 20));

        Button_Reset.setBackground(new java.awt.Color(34, 153, 68));
        Button_Reset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_Reset.setForeground(new java.awt.Color(255, 255, 255));
        Button_Reset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button_Reset.setText("Search");
        Button_Reset.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Button_Reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Reset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_Reset.setOpaque(true);
        Button_Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_ResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button_ResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button_ResetMouseExited(evt);
            }
        });
        add(Button_Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 70, 30));

        Field_Search.setForeground(new java.awt.Color(153, 0, 0));
        Field_Search.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Field_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Field_SearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Field_SearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Field_SearchKeyTyped(evt);
            }
        });
        add(Field_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 210, 30));

        Table_Log.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ScrollPane_Log.setViewportView(Table_Log);

        add(ScrollPane_Log, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 227, 840, 380));

        Background.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Background.setForeground(new java.awt.Color(153, 0, 0));
        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fys/Images/Background.png"))); // NOI18N
        Background.setOpaque(true);
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1280, 780));
    }// </editor-fold>//GEN-END:initComponents

    private void Label_LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_LogoMouseClicked
        FYS.getInstance().showPage(new Man_Home());
    }//GEN-LAST:event_Label_LogoMouseClicked

    private void Tab_GraphDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_GraphDataMouseClicked
        FYS.getInstance().showPage(new Man_Graphs());
    }//GEN-LAST:event_Tab_GraphDataMouseClicked

    private void Tab_GraphDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_GraphDataMouseEntered
        Tab_GraphData.setBackground(new java.awt.Color(255, 255, 255));
        Tab_GraphData.setForeground(new java.awt.Color(156, 10, 13));
    }//GEN-LAST:event_Tab_GraphDataMouseEntered

    private void Tab_GraphDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_GraphDataMouseExited
        Tab_GraphData.setBackground(new java.awt.Color(156, 10, 13));
        Tab_GraphData.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Tab_GraphDataMouseExited

    private void Tab_LogActivitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_LogActivitiesMouseClicked
        FYS.getInstance().showPage(new Man_LogActivities());
    }//GEN-LAST:event_Tab_LogActivitiesMouseClicked

    private void Tab_LogActivitiesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_LogActivitiesMouseEntered

    }//GEN-LAST:event_Tab_LogActivitiesMouseEntered

    private void Tab_LogActivitiesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_LogActivitiesMouseExited

    }//GEN-LAST:event_Tab_LogActivitiesMouseExited

    private void Label_CallManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_CallManualMouseClicked
        Manual_Panel.setVisible(true);
        Manual_Panel.setEnabled(true);
    }//GEN-LAST:event_Label_CallManualMouseClicked

    private void Box_TimeFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_TimeFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_TimeFrameActionPerformed

    private void Field_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Field_SearchKeyReleased

    }//GEN-LAST:event_Field_SearchKeyReleased

    private void Tab_LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_LogOutMouseClicked
        FYS.getInstance().showPage(new Man_LogOut());
    }//GEN-LAST:event_Tab_LogOutMouseClicked

    private void Tab_LogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_LogOutMouseEntered
        Tab_LogOut.setBackground(new java.awt.Color(255, 255, 255));
        Tab_LogOut.setForeground(new java.awt.Color(156, 10, 13));
    }//GEN-LAST:event_Tab_LogOutMouseEntered

    private void Tab_LogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_LogOutMouseExited
        Tab_LogOut.setBackground(new java.awt.Color(156, 10, 13));
        Tab_LogOut.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Tab_LogOutMouseExited

    private void Label_ManualExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_ManualExitMouseClicked
        Manual_Panel.setVisible(false);
        Manual_Panel.setEnabled(false);
    }//GEN-LAST:event_Label_ManualExitMouseClicked

    private void Field_SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Field_SearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_SearchKeyPressed

    private void Button_ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ResetMouseClicked
             try {
            String sql = "select * from log where employeeID=? OR tab=?  ";
                           pst = conn.prepareStatement(sql);
                            pst.setString(1, Field_Search.getText());
                            pst.setString(2, Field_Search.getText());
            rs = pst.executeQuery();
            Table_Log.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }          
    }//GEN-LAST:event_Button_ResetMouseClicked

    private void Button_ResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ResetMouseEntered
        Button_Reset.setBackground(new java.awt.Color(51, 136, 68));
    }//GEN-LAST:event_Button_ResetMouseEntered

    private void Button_ResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ResetMouseExited
        Button_Reset.setBackground(new java.awt.Color(34, 153, 68));
    }//GEN-LAST:event_Button_ResetMouseExited

    private void Field_SearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Field_SearchKeyTyped

    }//GEN-LAST:event_Field_SearchKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JComboBox Box_Case;
    private javax.swing.JComboBox Box_TimeFrame;
    private javax.swing.JLabel Button_Reset;
    private javax.swing.JTextField Field_Search;
    private javax.swing.JLabel Label_CallManual;
    private javax.swing.JLabel Label_Case;
    private javax.swing.JLabel Label_Info;
    private javax.swing.JLabel Label_Logo;
    private javax.swing.JLabel Label_ManualExit;
    private javax.swing.JLabel Label_Timeframe;
    private javax.swing.JLabel Label_Title;
    private javax.swing.JPanel Manual_Panel;
    private javax.swing.JScrollPane ScrollPane_Log;
    private javax.swing.JLabel Tab_GraphData;
    private javax.swing.JLabel Tab_LogActivities;
    private javax.swing.JLabel Tab_LogOut;
    private javax.swing.JTable Table_Log;
    // End of variables declaration//GEN-END:variables
}
