package fys;

public class Man_LogOut extends javax.swing.JPanel {

    public Man_LogOut() {
        initComponents();
        Manual_Panel.setVisible(false);
        Manual_Panel.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Manual_Panel = new javax.swing.JPanel();
        Label_ManualExit = new javax.swing.JLabel();
        Label_CallManual = new javax.swing.JLabel();
        Label_AccountType = new javax.swing.JLabel();
        Button_No = new javax.swing.JLabel();
        Button_Yes = new javax.swing.JLabel();
        Tab_GraphData = new javax.swing.JLabel();
        Tab_BaggageData = new javax.swing.JLabel();
        Tab_LogOut = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Background = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Manual_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Manual_Panel.setEnabled(false);
        Manual_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_ManualExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_ManualExit.setText("X");
        Label_ManualExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_ManualExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_ManualExitMouseClicked(evt);
            }
        });
        Manual_Panel.add(Label_ManualExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 20, 20));

        add(Manual_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 290, 590));

        Label_CallManual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_CallManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_CallManualMouseClicked(evt);
            }
        });
        add(Label_CallManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 50, 50));

        Label_AccountType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_AccountType.setForeground(new java.awt.Color(153, 0, 0));
        Label_AccountType.setText("Are you sure you want to log out of our fabulous fucking app?");
        add(Label_AccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        Button_No.setBackground(new java.awt.Color(34, 153, 68));
        Button_No.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_No.setForeground(new java.awt.Color(255, 255, 255));
        Button_No.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button_No.setText("No");
        Button_No.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_No.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_No.setOpaque(true);
        Button_No.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button_NoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button_NoMouseExited(evt);
            }
        });
        add(Button_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 130, -1));

        Button_Yes.setBackground(new java.awt.Color(34, 153, 68));
        Button_Yes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_Yes.setForeground(new java.awt.Color(255, 255, 255));
        Button_Yes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button_Yes.setText("Yes");
        Button_Yes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Yes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_Yes.setOpaque(true);
        Button_Yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_YesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button_YesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button_YesMouseExited(evt);
            }
        });
        add(Button_Yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 130, -1));

        Tab_GraphData.setBackground(new java.awt.Color(156, 10, 13));
        Tab_GraphData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tab_GraphData.setForeground(new java.awt.Color(255, 255, 255));
        Tab_GraphData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tab_GraphData.setText("Graph Data");
        Tab_GraphData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_GraphData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_GraphData.setOpaque(true);
        Tab_GraphData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_GraphDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab_GraphDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab_GraphDataMouseExited(evt);
            }
        });
        add(Tab_GraphData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, 40));

        Tab_BaggageData.setBackground(new java.awt.Color(156, 10, 13));
        Tab_BaggageData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tab_BaggageData.setForeground(new java.awt.Color(255, 255, 255));
        Tab_BaggageData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tab_BaggageData.setText("Baggage Data");
        Tab_BaggageData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_BaggageData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_BaggageData.setOpaque(true);
        Tab_BaggageData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_BaggageDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab_BaggageDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab_BaggageDataMouseExited(evt);
            }
        });
        add(Tab_BaggageData, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 250, 40));

        Tab_LogOut.setBackground(new java.awt.Color(255, 255, 255));
        Tab_LogOut.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tab_LogOut.setForeground(new java.awt.Color(156, 10, 13));
        Tab_LogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tab_LogOut.setText("Log Out");
        Tab_LogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_LogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_LogOut.setOpaque(true);
        add(Tab_LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 250, 40));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1360, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 500, 40));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 150, 540, 20));

        Background.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Background.setForeground(new java.awt.Color(153, 0, 0));
        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fys/Images/Background.png"))); // NOI18N
        Background.setOpaque(true);
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1280, 780));
    }// </editor-fold>//GEN-END:initComponents

    private void Tab_BaggageDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_BaggageDataMouseEntered
        Tab_BaggageData.setBackground(new java.awt.Color(255, 255, 255));
        Tab_BaggageData.setForeground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_Tab_BaggageDataMouseEntered

    private void Tab_BaggageDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_BaggageDataMouseExited
        Tab_BaggageData.setBackground(new java.awt.Color(153, 0, 0));
        Tab_BaggageData.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Tab_BaggageDataMouseExited

    private void Button_NoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_NoMouseEntered
        Button_No.setBackground(new java.awt.Color(51, 136, 68));
    }//GEN-LAST:event_Button_NoMouseEntered

    private void Button_NoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_NoMouseExited
        Button_No.setBackground(new java.awt.Color(34, 153, 68));
    }//GEN-LAST:event_Button_NoMouseExited

    private void Button_YesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_YesMouseEntered
        Button_Yes.setBackground(new java.awt.Color(51, 136, 68));
    }//GEN-LAST:event_Button_YesMouseEntered

    private void Button_YesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_YesMouseExited
        Button_Yes.setBackground(new java.awt.Color(34, 153, 68));
    }//GEN-LAST:event_Button_YesMouseExited

    private void Tab_GraphDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_GraphDataMouseEntered
        Tab_GraphData.setBackground(new java.awt.Color(255, 255, 255));
        Tab_GraphData.setForeground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_Tab_GraphDataMouseEntered

    private void Tab_GraphDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_GraphDataMouseExited
        Tab_GraphData.setBackground(new java.awt.Color(153, 0, 0));
        Tab_GraphData.setForeground(new java.awt.Color(255, 255, 255));
     }//GEN-LAST:event_Tab_GraphDataMouseExited

    private void Tab_BaggageDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_BaggageDataMouseClicked
        FYS.getInstance().showPage(new AppMan_ManageAccounts());
    }//GEN-LAST:event_Tab_BaggageDataMouseClicked

    private void Tab_GraphDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_GraphDataMouseClicked
        FYS.getInstance().showPage(new AppMan_NewAccount());
    }//GEN-LAST:event_Tab_GraphDataMouseClicked

    private void Button_YesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_YesMouseClicked
        FYS.getInstance().showPage(new Login());
    }//GEN-LAST:event_Button_YesMouseClicked

    private void Label_ManualExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_ManualExitMouseClicked
        Manual_Panel.setVisible(false);
        Manual_Panel.setEnabled(false);
    }//GEN-LAST:event_Label_ManualExitMouseClicked

    private void Label_CallManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_CallManualMouseClicked
        Manual_Panel.setVisible(true);
        Manual_Panel.setEnabled(true);
    }//GEN-LAST:event_Label_CallManualMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Button_No;
    private javax.swing.JLabel Button_Yes;
    private javax.swing.JLabel Label_AccountType;
    private javax.swing.JLabel Label_CallManual;
    private javax.swing.JLabel Label_ManualExit;
    private javax.swing.JPanel Manual_Panel;
    private javax.swing.JLabel Tab_BaggageData;
    private javax.swing.JLabel Tab_GraphData;
    private javax.swing.JLabel Tab_LogOut;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
