package fys;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

public class SerDesEmp_UpdateBaggage extends javax.swing.JPanel {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    boolean isSelected = false;

    public SerDesEmp_UpdateBaggage() {
        initComponents();
        Manual_Panel.setVisible(false);
        Manual_Panel.setEnabled(false);
        emptyfield_warning.setVisible(false);
        emptyfield_warning.setEnabled(false);
        
        conn = javaconnect.ConnecrDb();
        Update_table();
        
                ButtonGroup group = new ButtonGroup();
        group.add(Button_Found);
        group.add(Button_Retrieved);
        group.add(Button_NotFound);
        
    
    }
    



    private void Update_table() {
        try {
            String sql = "select  baggageID, brand, color, weight,dateadded, dateretrieved, flightnumber, state  from baggage "; 
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            Table_Cases.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        Label_Logo = new javax.swing.JLabel();
        Label_CallManual = new javax.swing.JLabel();
        Label_Search = new javax.swing.JLabel();
        Label_FlightNumber1 = new javax.swing.JLabel();
        Field_Search = new javax.swing.JTextField();
        ScrollPane_Cases = new javax.swing.JScrollPane();
        Table_Cases = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        Field_Description = new javax.swing.JTextArea();
        Label_BaggageInformation = new javax.swing.JLabel();
        Label_FlightNumber = new javax.swing.JLabel();
        Label_Brand = new javax.swing.JLabel();
        Label_Color = new javax.swing.JLabel();
        Label_Weight = new javax.swing.JLabel();
        Label_Description = new javax.swing.JLabel();
        Field_FlightNumber = new javax.swing.JTextField();
        Field_Brand = new javax.swing.JTextField();
        Field_Color = new javax.swing.JTextField();
        Field_BaggageID = new javax.swing.JTextField();
        Field_Weight = new javax.swing.JTextField();
        Button_Save = new javax.swing.JLabel();
        Button_Reset = new javax.swing.JLabel();
        Button_PDF = new javax.swing.JLabel();
        emptyfield_warning = new javax.swing.JLabel();
        Field_DateFound = new com.toedter.calendar.JDateChooser();
        Label_Date2 = new javax.swing.JLabel();
        Label_Date3 = new javax.swing.JLabel();
        Tab_NewCase = new javax.swing.JLabel();
        Tab_UpdateBaggage = new javax.swing.JLabel();
        Tab_AddBaggage = new javax.swing.JLabel();
        Tab_LogOut = new javax.swing.JLabel();
        Tab_UpdateCase = new javax.swing.JLabel();
        Button_Retrieved = new javax.swing.JRadioButton();
        Button_Found = new javax.swing.JRadioButton();
        Button_NotFound = new javax.swing.JRadioButton();
        Background = new javax.swing.JLabel();
        Manual_Panel = new javax.swing.JPanel();
        Label_ManualExit = new javax.swing.JLabel();
        Label_Title = new javax.swing.JLabel();
        Label_Info = new javax.swing.JLabel();
        serDesEmp_LogOut1 = new fys.SerDesEmp_LogOut();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_LogoMouseClicked(evt);
            }
        });
        add(Label_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 60));

        Label_CallManual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_CallManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_CallManualMouseClicked(evt);
            }
        });
        add(Label_CallManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 50, 50));

        Label_Search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_Search.setForeground(new java.awt.Color(153, 0, 0));
        Label_Search.setText("Search:");
        add(Label_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, 30));

        Label_FlightNumber1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_FlightNumber1.setForeground(new java.awt.Color(153, 0, 0));
        Label_FlightNumber1.setText("Baggage ID:");
        add(Label_FlightNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, -1, -1));

        Field_Search.setForeground(new java.awt.Color(153, 0, 0));
        Field_Search.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Field_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Field_SearchKeyReleased(evt);
            }
        });
        add(Field_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 210, 30));

        Table_Cases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Cases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_CasesMouseClicked(evt);
            }
        });
        ScrollPane_Cases.setViewportView(Table_Cases);

        add(ScrollPane_Cases, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 730, 340));

        Field_Description.setColumns(20);
        Field_Description.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Field_Description.setRows(5);
        Field_Description.setBorder(null);
        jScrollPane1.setViewportView(Field_Description);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 370, 230, 110));

        Label_BaggageInformation.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        Label_BaggageInformation.setForeground(new java.awt.Color(153, 0, 0));
        Label_BaggageInformation.setText("Baggage Information:");
        add(Label_BaggageInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, -1, -1));

        Label_FlightNumber.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_FlightNumber.setForeground(new java.awt.Color(153, 0, 0));
        Label_FlightNumber.setText("Flight Number:");
        add(Label_FlightNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, -1, -1));

        Label_Brand.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_Brand.setForeground(new java.awt.Color(153, 0, 0));
        Label_Brand.setText("Brand:");
        add(Label_Brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, -1, -1));

        Label_Color.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_Color.setForeground(new java.awt.Color(153, 0, 0));
        Label_Color.setText("Color:");
        add(Label_Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, -1, -1));

        Label_Weight.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_Weight.setForeground(new java.awt.Color(153, 0, 0));
        Label_Weight.setText("Weight:");
        add(Label_Weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, -1, -1));

        Label_Description.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_Description.setForeground(new java.awt.Color(153, 0, 0));
        Label_Description.setText("Description:");
        add(Label_Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, -1, -1));

        Field_FlightNumber.setForeground(new java.awt.Color(153, 0, 0));
        Field_FlightNumber.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_FlightNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 250, 230, 30));

        Field_Brand.setForeground(new java.awt.Color(153, 0, 0));
        Field_Brand.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_Brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 280, 230, 30));

        Field_Color.setForeground(new java.awt.Color(153, 0, 0));
        Field_Color.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 230, 30));

        Field_BaggageID.setForeground(new java.awt.Color(153, 0, 0));
        Field_BaggageID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_BaggageID, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, 230, 30));

        Field_Weight.setForeground(new java.awt.Color(153, 0, 0));
        Field_Weight.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_Weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, 230, 30));

        Button_Save.setBackground(new java.awt.Color(34, 153, 68));
        Button_Save.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_Save.setForeground(new java.awt.Color(255, 255, 255));
        Button_Save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button_Save.setText("Save");
        Button_Save.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Button_Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Save.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_Save.setOpaque(true);
        Button_Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_SaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button_SaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button_SaveMouseExited(evt);
            }
        });
        add(Button_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, 130, 30));

        Button_Reset.setBackground(new java.awt.Color(34, 153, 68));
        Button_Reset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_Reset.setForeground(new java.awt.Color(255, 255, 255));
        Button_Reset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button_Reset.setText("Reset");
        Button_Reset.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Button_Reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Reset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_Reset.setOpaque(true);
        Button_Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_ResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button_ResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button_ResetMouseExited(evt);
            }
        });
        add(Button_Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 600, 130, 30));

        Button_PDF.setBackground(new java.awt.Color(34, 153, 68));
        Button_PDF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_PDF.setForeground(new java.awt.Color(255, 255, 255));
        Button_PDF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button_PDF.setText("Make PDF");
        Button_PDF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Button_PDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_PDF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_PDF.setOpaque(true);
        Button_PDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_PDFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button_PDFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button_PDFMouseExited(evt);
            }
        });
        add(Button_PDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, 130, 30));

        emptyfield_warning.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emptyfield_warning.setForeground(new java.awt.Color(153, 0, 0));
        emptyfield_warning.setText("* One or more required fields are empty. Please fill them in and try again.");
        add(emptyfield_warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, -1, -1));
        add(Field_DateFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, 230, 30));

        Label_Date2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_Date2.setForeground(new java.awt.Color(153, 0, 0));
        Label_Date2.setText("State of baggage:");
        add(Label_Date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, 140, 20));

        Label_Date3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_Date3.setForeground(new java.awt.Color(153, 0, 0));
        Label_Date3.setText("Retrieved Date:");
        add(Label_Date3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, 140, 20));

        Tab_NewCase.setBackground(new java.awt.Color(156, 0, 0));
        Tab_NewCase.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        Tab_NewCase.setForeground(new java.awt.Color(255, 255, 255));
        Tab_NewCase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tab_NewCase.setText("New Case");
        Tab_NewCase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_NewCase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_NewCase.setMaximumSize(new java.awt.Dimension(186, 27));
        Tab_NewCase.setMinimumSize(new java.awt.Dimension(186, 27));
        Tab_NewCase.setOpaque(true);
        Tab_NewCase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_NewCaseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab_NewCaseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab_NewCaseMouseExited(evt);
            }
        });
        add(Tab_NewCase, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 240, 40));

        Tab_UpdateBaggage.setBackground(new java.awt.Color(255, 255, 255));
        Tab_UpdateBaggage.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        Tab_UpdateBaggage.setForeground(new java.awt.Color(156, 0, 0));
        Tab_UpdateBaggage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tab_UpdateBaggage.setText("Update Baggage Case");
        Tab_UpdateBaggage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_UpdateBaggage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_UpdateBaggage.setOpaque(true);
        Tab_UpdateBaggage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_UpdateBaggageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab_UpdateBaggageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab_UpdateBaggageMouseExited(evt);
            }
        });
        add(Tab_UpdateBaggage, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 230, 40));

        Tab_AddBaggage.setBackground(new java.awt.Color(156, 0, 0));
        Tab_AddBaggage.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        Tab_AddBaggage.setForeground(new java.awt.Color(255, 255, 255));
        Tab_AddBaggage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tab_AddBaggage.setText("Add Extra Baggage");
        Tab_AddBaggage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_AddBaggage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_AddBaggage.setOpaque(true);
        Tab_AddBaggage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_AddBaggageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab_AddBaggageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab_AddBaggageMouseExited(evt);
            }
        });
        add(Tab_AddBaggage, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 230, 40));

        Tab_LogOut.setBackground(new java.awt.Color(156, 0, 0));
        Tab_LogOut.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        Tab_LogOut.setForeground(new java.awt.Color(255, 255, 255));
        Tab_LogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tab_LogOut.setText("Log Out");
        Tab_LogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_LogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_LogOut.setOpaque(true);
        Tab_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_LogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab_LogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab_LogOutMouseExited(evt);
            }
        });
        add(Tab_LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 110, 230, 40));

        Tab_UpdateCase.setBackground(new java.awt.Color(156, 0, 0));
        Tab_UpdateCase.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        Tab_UpdateCase.setForeground(new java.awt.Color(255, 255, 255));
        Tab_UpdateCase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tab_UpdateCase.setText("Update Client Case");
        Tab_UpdateCase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_UpdateCase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_UpdateCase.setMaximumSize(new java.awt.Dimension(186, 27));
        Tab_UpdateCase.setMinimumSize(new java.awt.Dimension(186, 27));
        Tab_UpdateCase.setOpaque(true);
        Tab_UpdateCase.setPreferredSize(new java.awt.Dimension(186, 27));
        Tab_UpdateCase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_UpdateCaseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab_UpdateCaseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab_UpdateCaseMouseExited(evt);
            }
        });
        add(Tab_UpdateCase, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 240, 40));

        Button_Retrieved.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(Button_Retrieved);
        Button_Retrieved.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_Retrieved.setForeground(new java.awt.Color(156, 0, 0));
        Button_Retrieved.setText("Retrieved");
        Button_Retrieved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RetrievedActionPerformed(evt);
            }
        });
        add(Button_Retrieved, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 520, 90, -1));

        Button_Found.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(Button_Found);
        Button_Found.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_Found.setForeground(new java.awt.Color(156, 0, 0));
        Button_Found.setText("Found");
        Button_Found.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_FoundActionPerformed(evt);
            }
        });
        add(Button_Found, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 520, -1, -1));

        Button_NotFound.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(Button_NotFound);
        Button_NotFound.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Button_NotFound.setForeground(new java.awt.Color(156, 0, 0));
        Button_NotFound.setText("Not Found");
        Button_NotFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_NotFoundActionPerformed(evt);
            }
        });
        add(Button_NotFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 520, -1, -1));

        Background.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Background.setForeground(new java.awt.Color(153, 0, 0));
        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fys/Images/Background.png"))); // NOI18N
        Background.setOpaque(true);
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1280, 780));

        Manual_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Manual_Panel.setEnabled(false);
        Manual_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_ManualExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_ManualExit.setText("X");
        Label_ManualExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_ManualExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_ManualExitMouseClicked(evt);
            }
        });
        Manual_Panel.add(Label_ManualExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 20, 20));

        Label_Title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Title.setForeground(new java.awt.Color(153, 0, 0));
        Label_Title.setText("Manual");
        Manual_Panel.add(Label_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));

        Label_Info.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_Info.setForeground(new java.awt.Color(153, 0, 0));
        Label_Info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Info.setText("<html>\nOn the left side of the screen, fill in the search term\nfor the case you wish to update. This will generate\na list of cases that match your search in the table below. \nClick on the desired table to fill the list of fields to the right.\nFrom here you can change or delete the case's data. If you \nwish to start over, click the 'Reset' button to return the\nfields to their original values. If you're satisfied with the\nchanges you've made, click the 'Save' button to make\nthem permanent.\n<br>\n<br>\nRequired fields are marked by a *.");
        Label_Info.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Manual_Panel.add(Label_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 420));

        add(Manual_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 290, 590));
        add(serDesEmp_LogOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-410, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    private void Button_ResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ResetMouseEntered
        Button_Reset.setBackground(new java.awt.Color(51, 136, 68));
    }//GEN-LAST:event_Button_ResetMouseEntered

    private void Button_ResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ResetMouseExited
        Button_Reset.setBackground(new java.awt.Color(34, 153, 68));
    }//GEN-LAST:event_Button_ResetMouseExited

    private void Button_SaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SaveMouseEntered
        Button_Save.setBackground(new java.awt.Color(51, 136, 68));

    }//GEN-LAST:event_Button_SaveMouseEntered

    private void Button_SaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SaveMouseExited
        Button_Save.setBackground(new java.awt.Color(34, 153, 68));

    }//GEN-LAST:event_Button_SaveMouseExited

    private void Field_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Field_SearchKeyReleased

        try {
            String sql = "select * from baggage where clientID=? OR baggageID=? OR flightnumber=? OR brand=? OR color=? OR weight=? OR description=? OR dateadded=? OR dateretrieved=? OR state=? ";

            pst = conn.prepareStatement(sql);
            pst.setString(1, Field_Search.getText());
            pst.setString(2, Field_Search.getText());
            pst.setString(3, Field_Search.getText());
            pst.setString(4, Field_Search.getText());
            pst.setString(5, Field_Search.getText());
            pst.setString(6, Field_Search.getText());
            pst.setString(7, Field_Search.getText());
            pst.setString(8, Field_Search.getText());
            pst.setString(9, Field_Search.getText());
            pst.setString(10, Field_Search.getText());
            pst.setString(11, Field_Search.getText());

            rs = pst.executeQuery();
            if (rs.next()) {

                String add1 = rs.getString("baggageID");
                Field_BaggageID.setText(add1);
                String add2 = rs.getString("flightnumber");
                Field_FlightNumber.setText(add2);
                String add3 = rs.getString("brand");
                Field_Brand.setText(add3);
                String add4 = rs.getString("color");
                Field_Color.setText(add4);
                String add5 = rs.getString("weight");
                Field_Weight.setText(add5);
                String add6 = rs.getString("description");
                Field_Description.setText(add6);

            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_Field_SearchKeyReleased

    private void Label_ManualExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_ManualExitMouseClicked
        Manual_Panel.setVisible(false);
        Manual_Panel.setEnabled(false);
    }//GEN-LAST:event_Label_ManualExitMouseClicked

    private void Label_CallManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_CallManualMouseClicked
        Manual_Panel.setVisible(true);
        Manual_Panel.setEnabled(true);
    }//GEN-LAST:event_Label_CallManualMouseClicked

    private void Table_CasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_CasesMouseClicked
        try {
            int row = Table_Cases.getSelectedRow();
            String Table_click = (Table_Cases.getModel().getValueAt(row, 0).toString());
            String sql = "select * from baggage where baggageID='" + Table_click + "' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {

                String add1 = rs.getString("baggageID"); 
                Field_BaggageID.setText(add1);
                Field_BaggageID.setEditable(false);
                String add2 = rs.getString("flightnumber");
                Field_FlightNumber.setText(add2);
                String add3 = rs.getString("brand");
                Field_Brand.setText(add3);
                String add4 = rs.getString("color");
                Field_Color.setText(add4);
                String add5 = rs.getString("weight");
                Field_Weight.setText(add5);
                String add6 = rs.getString("description");
                Field_Description.setText(add6);
                rs.getString("state");
                if (rs.getString("state").equals("found")) {
                    Button_Found.setSelected(true);
                }
                else if (rs.getString("state").equals("not found")) {
                    Button_NotFound.setSelected(true);
                }
                else if (rs.getString("state").equals("retrieved")) {
                    Button_Retrieved.setSelected(true);
                }



            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }


    }//GEN-LAST:event_Table_CasesMouseClicked

    private void Button_SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SaveMouseClicked

                    try {
                           
                        String value1 = Field_FlightNumber.getText();
                        String value2 = Field_Brand.getText();
                        String value3 = Field_Color.getText();
                        String value4 = Field_Weight.getText();
                        String value5 = Field_Description.getText();
                        String value6 =((JTextField)Field_DateFound.getDateEditor().getUiComponent()).getText();
                         String value7 = "";               
                        if (Button_Found.isSelected()) {
                         value7 = "found";
                         }
                          else if (Button_NotFound.isSelected()) {
                         value7 = "not found";
                     }
                        else if (Button_Retrieved.isSelected()) {
                         value7 = "retrieved";
                }


                        String sql = "update baggage set flightnumber = '" + value1 + "',brand = '" + value2 + "',color = '" + value3 + "',weight = '" + value4 + "',description = '" + value5 + "' ,dateretrieved = '" + value6 + "',state = '" + value7 + "'where flightnumber='" + value1 + "' ";
                        pst = conn.prepareStatement(sql);
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "Updated");

                    } catch (Exception e) {

                        JOptionPane.showMessageDialog(null, e);
                    }
                    Update_table();

                
               
            
    }//GEN-LAST:event_Button_SaveMouseClicked

    private void Button_ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ResetMouseClicked
        Field_BaggageID.setText("");
        Field_FlightNumber.setText("");
        Field_Brand.setText("");
        Field_Color.setText("");
        Field_Weight.setText("");
        Field_Description.setText("");
        
    }//GEN-LAST:event_Button_ResetMouseClicked

    private void Label_LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_LogoMouseClicked
        FYS.getInstance().showPage(new SerDesEmp_Home());
    }//GEN-LAST:event_Label_LogoMouseClicked

    private void Button_PDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_PDFMouseClicked

        //alles uit het updatecase screen
       /* int date = 0;

        String brand = Field_Brand.getText();
        String color = Field_Color.getText();
        String weight = Field_Weight.getText();
        String description = Field_Description.getText();

        //description  generate and save pdf
        PDFGenerator pdf = new PDFGenerator();
        pdf.generate( brand, color, weight, description);

        //  moet aangepast worden zodra doreen klaar heeft wat er in gevuld moet worden
        pdf.save(firstname + lastname + zipcode + ".pdf");*/
    }//GEN-LAST:event_Button_PDFMouseClicked

    private void Button_PDFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_PDFMouseEntered
        Button_Save.setBackground(new java.awt.Color(51, 136, 68));
    }//GEN-LAST:event_Button_PDFMouseEntered

    private void Button_PDFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_PDFMouseExited
        Button_Reset.setBackground(new java.awt.Color(34, 153, 68));
    }//GEN-LAST:event_Button_PDFMouseExited

    private void Button_FoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_FoundActionPerformed
       state = "found";
    }//GEN-LAST:event_Button_FoundActionPerformed

    private void Button_RetrievedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RetrievedActionPerformed
       state = "retrieved";
    }//GEN-LAST:event_Button_RetrievedActionPerformed

    private void Button_NotFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_NotFoundActionPerformed
       state = "not found";
    }//GEN-LAST:event_Button_NotFoundActionPerformed

    private void Tab_UpdateBaggageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_UpdateBaggageMouseClicked
        FYS.getInstance().showPage(new SerDesEmp_UpdateBaggage());

    }//GEN-LAST:event_Tab_UpdateBaggageMouseClicked

    private void Tab_UpdateBaggageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_UpdateBaggageMouseEntered

    }//GEN-LAST:event_Tab_UpdateBaggageMouseEntered

    private void Tab_UpdateBaggageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_UpdateBaggageMouseExited

    }//GEN-LAST:event_Tab_UpdateBaggageMouseExited

    private void Tab_AddBaggageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_AddBaggageMouseClicked
        FYS.getInstance().showPage(new SerDesEmp_AddBagage());
        Tab_AddBaggage.setForeground(new java.awt.Color(153, 0, 0));
        Tab_AddBaggage.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Tab_AddBaggageMouseClicked

    private void Tab_AddBaggageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_AddBaggageMouseEntered
        Tab_AddBaggage.setBackground(new java.awt.Color(255, 255, 255));
        Tab_AddBaggage.setForeground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_Tab_AddBaggageMouseEntered

    private void Tab_AddBaggageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_AddBaggageMouseExited
        Tab_AddBaggage.setBackground(new java.awt.Color(153, 0, 0));
        Tab_AddBaggage.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Tab_AddBaggageMouseExited

    private void Tab_LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_LogOutMouseClicked
        FYS.getInstance().showPage(new SerDesEmp_LogOut());
        Tab_LogOut.setForeground(new java.awt.Color(153, 0, 0));
        Tab_LogOut.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Tab_LogOutMouseClicked

    private void Tab_LogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_LogOutMouseEntered
        Tab_LogOut.setBackground(new java.awt.Color(255, 255, 255));
        Tab_LogOut.setForeground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_Tab_LogOutMouseEntered

    private void Tab_LogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_LogOutMouseExited
        Tab_LogOut.setBackground(new java.awt.Color(153, 0, 0));
        Tab_LogOut.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Tab_LogOutMouseExited

    private void Tab_UpdateCaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_UpdateCaseMouseClicked
        FYS.getInstance().showPage(new SerDesEmp_UpdateCase());
        Tab_UpdateCase.setBackground(new java.awt.Color(255, 255, 255));
        Tab_UpdateCase.setForeground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_Tab_UpdateCaseMouseClicked

    private void Tab_UpdateCaseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_UpdateCaseMouseEntered
        Tab_UpdateCase.setBackground(new java.awt.Color(255, 255, 255));
        Tab_UpdateCase.setForeground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_Tab_UpdateCaseMouseEntered

    private void Tab_UpdateCaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_UpdateCaseMouseExited
        Tab_UpdateCase.setBackground(new java.awt.Color(153, 0, 0));
        Tab_UpdateCase.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Tab_UpdateCaseMouseExited

    private void Tab_NewCaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_NewCaseMouseClicked
        FYS.getInstance().showPage(new SerDesEmp_NewCase());
    }//GEN-LAST:event_Tab_NewCaseMouseClicked

    private void Tab_NewCaseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_NewCaseMouseEntered
        Tab_NewCase.setBackground(new java.awt.Color(255, 255, 255));
        Tab_NewCase.setForeground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_Tab_NewCaseMouseEntered

    private void Tab_NewCaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_NewCaseMouseExited
        Tab_NewCase.setBackground(new java.awt.Color(153, 0, 0));
        Tab_NewCase.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Tab_NewCaseMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JRadioButton Button_Found;
    private javax.swing.JRadioButton Button_NotFound;
    private javax.swing.JLabel Button_PDF;
    private javax.swing.JLabel Button_Reset;
    private javax.swing.JRadioButton Button_Retrieved;
    private javax.swing.JLabel Button_Save;
    private javax.swing.JTextField Field_BaggageID;
    private javax.swing.JTextField Field_Brand;
    private javax.swing.JTextField Field_Color;
    private com.toedter.calendar.JDateChooser Field_DateFound;
    private javax.swing.JTextArea Field_Description;
    private javax.swing.JTextField Field_FlightNumber;
    private javax.swing.JTextField Field_Search;
    private javax.swing.JTextField Field_Weight;
    private javax.swing.JLabel Label_BaggageInformation;
    private javax.swing.JLabel Label_Brand;
    private javax.swing.JLabel Label_CallManual;
    private javax.swing.JLabel Label_Color;
    private javax.swing.JLabel Label_Date2;
    private javax.swing.JLabel Label_Date3;
    private javax.swing.JLabel Label_Description;
    private javax.swing.JLabel Label_FlightNumber;
    private javax.swing.JLabel Label_FlightNumber1;
    private javax.swing.JLabel Label_Info;
    private javax.swing.JLabel Label_Logo;
    private javax.swing.JLabel Label_ManualExit;
    private javax.swing.JLabel Label_Search;
    private javax.swing.JLabel Label_Title;
    private javax.swing.JLabel Label_Weight;
    private javax.swing.JPanel Manual_Panel;
    private javax.swing.JScrollPane ScrollPane_Cases;
    private javax.swing.JLabel Tab_AddBaggage;
    private javax.swing.JLabel Tab_LogOut;
    private javax.swing.JLabel Tab_NewCase;
    private javax.swing.JLabel Tab_UpdateBaggage;
    private javax.swing.JLabel Tab_UpdateCase;
    private javax.swing.JTable Table_Cases;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel emptyfield_warning;
    private javax.swing.JScrollPane jScrollPane1;
    private fys.SerDesEmp_LogOut serDesEmp_LogOut1;
    // End of variables declaration//GEN-END:variables

private String state;
}
