package fys;

import javax.swing.ImageIcon;

public class SerDesEmp_UpdateCase extends javax.swing.JPanel {

    public SerDesEmp_UpdateCase() {
        initComponents();
        Manual_Panel.setVisible(false);
        Manual_Panel.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Manual_Panel = new javax.swing.JPanel();
        Label_ManualExit = new javax.swing.JLabel();
        Label_CallManual = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        employee_id = new javax.swing.JLabel();
        employeeid_field = new javax.swing.JTextField();
        first_name = new javax.swing.JLabel();
        firstname_field = new javax.swing.JTextField();
        last_name = new javax.swing.JLabel();
        lastname_field = new javax.swing.JTextField();
        updatecase_button = new javax.swing.JLabel();
        reset_button = new javax.swing.JLabel();
        save_button = new javax.swing.JLabel();
        LogOut_button2 = new javax.swing.JLabel();
        newbagageaccount_button = new javax.swing.JLabel();
        employee_id1 = new javax.swing.JLabel();
        employeeid_field1 = new javax.swing.JTextField();
        update_type = new javax.swing.JLabel();
        employeeid_field2 = new javax.swing.JTextField();
        email3 = new javax.swing.JLabel();
        email_field3 = new javax.swing.JTextField();
        employee_id4 = new javax.swing.JLabel();
        employeeid_field3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        LogOut_button4 = new javax.swing.JLabel();
        newclientaccount_button = new javax.swing.JLabel();
        Typebagage_Rbutton = new javax.swing.JRadioButton();
        employee_id5 = new javax.swing.JLabel();
        Typeclient_Rbutton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Label_Search = new javax.swing.JLabel();
        Field_Search1 = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Manual_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Manual_Panel.setEnabled(false);
        Manual_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_ManualExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_ManualExit.setText("X");
        Label_ManualExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_ManualExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_ManualExitMouseClicked(evt);
            }
        });
        Manual_Panel.add(Label_ManualExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 20, 20));

        add(Manual_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 290, 590));

        Label_CallManual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_CallManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_CallManualMouseClicked(evt);
            }
        });
        add(Label_CallManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 50, 50));

        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 70));

        employee_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employee_id.setForeground(new java.awt.Color(153, 0, 0));
        employee_id.setText("Bagage number:");
        add(employee_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        employeeid_field.setForeground(new java.awt.Color(153, 0, 0));
        employeeid_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(employeeid_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 350, 30));

        first_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        first_name.setForeground(new java.awt.Color(153, 0, 0));
        first_name.setText("Brand:");
        add(first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        firstname_field.setForeground(new java.awt.Color(153, 0, 0));
        firstname_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(firstname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 350, 30));

        last_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        last_name.setForeground(new java.awt.Color(153, 0, 0));
        last_name.setText("Color:");
        add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        lastname_field.setForeground(new java.awt.Color(153, 0, 0));
        lastname_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(lastname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 350, 30));

        updatecase_button.setBackground(new java.awt.Color(255, 255, 255));
        updatecase_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        updatecase_button.setForeground(new java.awt.Color(156, 0, 0));
        updatecase_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatecase_button.setText("Update Case");
        updatecase_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatecase_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updatecase_button.setOpaque(true);
        updatecase_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updatecase_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updatecase_buttonMouseExited(evt);
            }
        });
        add(updatecase_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 250, 40));

        reset_button.setBackground(new java.awt.Color(34, 153, 68));
        reset_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        reset_button.setForeground(new java.awt.Color(255, 255, 255));
        reset_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reset_button.setText("Reset");
        reset_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reset_button.setOpaque(true);
        reset_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reset_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reset_buttonMouseExited(evt);
            }
        });
        add(reset_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 600, 130, -1));

        save_button.setBackground(new java.awt.Color(34, 153, 68));
        save_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        save_button.setForeground(new java.awt.Color(255, 255, 255));
        save_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save_button.setText("Save");
        save_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save_button.setOpaque(true);
        save_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                save_buttonMouseExited(evt);
            }
        });
        add(save_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 600, 130, -1));

        LogOut_button2.setBackground(new java.awt.Color(156, 10, 13));
        LogOut_button2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LogOut_button2.setForeground(new java.awt.Color(255, 255, 255));
        LogOut_button2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOut_button2.setText("Log Out");
        LogOut_button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut_button2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogOut_button2.setOpaque(true);
        LogOut_button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOut_button2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOut_button2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOut_button2MouseExited(evt);
            }
        });
        add(LogOut_button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 250, 40));

        newbagageaccount_button.setBackground(new java.awt.Color(156, 0, 0));
        newbagageaccount_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newbagageaccount_button.setForeground(new java.awt.Color(255, 255, 255));
        newbagageaccount_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newbagageaccount_button.setText("New Bagage Case");
        newbagageaccount_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newbagageaccount_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newbagageaccount_button.setOpaque(true);
        newbagageaccount_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newbagageaccount_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newbagageaccount_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newbagageaccount_buttonMouseExited(evt);
            }
        });
        add(newbagageaccount_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 250, 40));

        employee_id1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employee_id1.setForeground(new java.awt.Color(153, 0, 0));
        employee_id1.setText("Description:");
        add(employee_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        employeeid_field1.setForeground(new java.awt.Color(153, 0, 0));
        employeeid_field1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(employeeid_field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 350, 100));

        update_type.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        update_type.setForeground(new java.awt.Color(153, 0, 0));
        update_type.setText("Update Type");
        add(update_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        employeeid_field2.setForeground(new java.awt.Color(153, 0, 0));
        employeeid_field2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(employeeid_field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 350, 30));

        email3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email3.setForeground(new java.awt.Color(153, 0, 0));
        email3.setText("Weight:");
        add(email3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        email_field3.setForeground(new java.awt.Color(153, 0, 0));
        email_field3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(email_field3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 350, 30));

        employee_id4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employee_id4.setForeground(new java.awt.Color(153, 0, 0));
        employee_id4.setText("Flight number:");
        add(employee_id4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        employeeid_field3.setForeground(new java.awt.Color(153, 0, 0));
        employeeid_field3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(employeeid_field3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 350, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1280, 20));

        LogOut_button4.setBackground(new java.awt.Color(156, 10, 13));
        LogOut_button4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LogOut_button4.setForeground(new java.awt.Color(255, 255, 255));
        LogOut_button4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOut_button4.setText("Log Out");
        LogOut_button4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut_button4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogOut_button4.setOpaque(true);
        LogOut_button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOut_button4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOut_button4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOut_button4MouseExited(evt);
            }
        });
        add(LogOut_button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 250, 40));

        newclientaccount_button.setBackground(new java.awt.Color(156, 0, 0));
        newclientaccount_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newclientaccount_button.setForeground(new java.awt.Color(255, 255, 255));
        newclientaccount_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newclientaccount_button.setText("New Client Case");
        newclientaccount_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newclientaccount_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newclientaccount_button.setOpaque(true);
        newclientaccount_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newclientaccount_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newclientaccount_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newclientaccount_buttonMouseExited(evt);
            }
        });
        add(newclientaccount_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 40));

        Typebagage_Rbutton.setBackground(new java.awt.Color(255, 255, 255));
        Typebagage_Rbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Typebagage_Rbutton.setForeground(new java.awt.Color(153, 0, 0));
        Typebagage_Rbutton.setText("Bagage Case");
        add(Typebagage_Rbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        employee_id5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employee_id5.setForeground(new java.awt.Color(153, 0, 0));
        employee_id5.setText("Client Number:");
        add(employee_id5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        Typeclient_Rbutton.setBackground(new java.awt.Color(255, 255, 255));
        Typeclient_Rbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Typeclient_Rbutton.setForeground(new java.awt.Color(153, 0, 0));
        Typeclient_Rbutton.setText("Client Case");
        add(Typeclient_Rbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 247, 600, 370));

        Label_Search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_Search.setForeground(new java.awt.Color(153, 0, 0));
        Label_Search.setText("Search:");
        add(Label_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, 30));

        Field_Search1.setForeground(new java.awt.Color(153, 0, 0));
        Field_Search1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Field_Search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Field_Search1KeyReleased(evt);
            }
        });
        add(Field_Search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 210, 30));

        Background.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Background.setForeground(new java.awt.Color(153, 0, 0));
        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fys/Images/Background.png"))); // NOI18N
        Background.setOpaque(true);
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1280, 780));
    }// </editor-fold>//GEN-END:initComponents

    private void updatecase_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatecase_buttonMouseEntered
        updatecase_button.setBackground(new java.awt.Color(255, 255, 255));
        updatecase_button.setForeground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_updatecase_buttonMouseEntered

    private void updatecase_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatecase_buttonMouseExited
        updatecase_button.setBackground(new java.awt.Color(153, 0, 0));

        updatecase_button.setForeground(new java.awt.Color(255, 255, 255));

    }//GEN-LAST:event_updatecase_buttonMouseExited


    private void reset_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_buttonMouseEntered
        reset_button.setBackground(new java.awt.Color(51, 136, 68));
    }//GEN-LAST:event_reset_buttonMouseEntered

    private void reset_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_buttonMouseExited
        reset_button.setBackground(new java.awt.Color(34, 153, 68));
    }//GEN-LAST:event_reset_buttonMouseExited

    private void save_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseEntered
        save_button.setBackground(new java.awt.Color(51, 136, 68));

    }//GEN-LAST:event_save_buttonMouseEntered

    private void save_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseExited
        save_button.setBackground(new java.awt.Color(34, 153, 68));

    }//GEN-LAST:event_save_buttonMouseExited

    private void newbagageaccount_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newbagageaccount_buttonMouseEntered
    }//GEN-LAST:event_newbagageaccount_buttonMouseEntered

    private void newbagageaccount_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newbagageaccount_buttonMouseExited

     }//GEN-LAST:event_newbagageaccount_buttonMouseExited

    private void LogOut_button2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_button2MouseExited
        LogOut_button2.setBackground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_LogOut_button2MouseExited

    private void LogOut_button2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_button2MouseEntered
        LogOut_button2.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_LogOut_button2MouseEntered

    private void newbagageaccount_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newbagageaccount_buttonMouseClicked
        FYS.getInstance().showPage(new SerDesEmp_NewCase());
    }//GEN-LAST:event_newbagageaccount_buttonMouseClicked

    private void LogOut_button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_button2MouseClicked
        FYS.getInstance().showPage(new SerDesEmp_LogOut());
    }//GEN-LAST:event_LogOut_button2MouseClicked

    private void LogOut_button4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_button4MouseClicked
        FYS.getInstance().showPage(new SerDesEmp_LogOut());
    }//GEN-LAST:event_LogOut_button4MouseClicked

    private void LogOut_button4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_button4MouseEntered
        LogOut_button2.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_LogOut_button4MouseEntered

    private void LogOut_button4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_button4MouseExited
        LogOut_button2.setBackground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_LogOut_button4MouseExited

    private void newclientaccount_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newclientaccount_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_newclientaccount_buttonMouseClicked

    private void newclientaccount_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newclientaccount_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_newclientaccount_buttonMouseEntered

    private void newclientaccount_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newclientaccount_buttonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_newclientaccount_buttonMouseExited

    private void Field_Search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Field_Search1KeyReleased


    }//GEN-LAST:event_Field_Search1KeyReleased

    private void Label_ManualExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_ManualExitMouseClicked
        Manual_Panel.setVisible(false);
        Manual_Panel.setEnabled(false);
    }//GEN-LAST:event_Label_ManualExitMouseClicked

    private void Label_CallManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_CallManualMouseClicked
        Manual_Panel.setVisible(true);
        Manual_Panel.setEnabled(true);
    }//GEN-LAST:event_Label_CallManualMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField Field_Search1;
    private javax.swing.JLabel Label_CallManual;
    private javax.swing.JLabel Label_ManualExit;
    private javax.swing.JLabel Label_Search;
    private javax.swing.JLabel LogOut_button2;
    private javax.swing.JLabel LogOut_button4;
    private javax.swing.JPanel Manual_Panel;
    private javax.swing.JRadioButton Typebagage_Rbutton;
    private javax.swing.JRadioButton Typeclient_Rbutton;
    private javax.swing.JLabel email3;
    private javax.swing.JTextField email_field3;
    private javax.swing.JLabel employee_id;
    private javax.swing.JLabel employee_id1;
    private javax.swing.JLabel employee_id4;
    private javax.swing.JLabel employee_id5;
    private javax.swing.JTextField employeeid_field;
    private javax.swing.JTextField employeeid_field1;
    private javax.swing.JTextField employeeid_field2;
    private javax.swing.JTextField employeeid_field3;
    private javax.swing.JLabel first_name;
    private javax.swing.JTextField firstname_field;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel last_name;
    private javax.swing.JTextField lastname_field;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel newbagageaccount_button;
    private javax.swing.JLabel newclientaccount_button;
    private javax.swing.JLabel reset_button;
    private javax.swing.JLabel save_button;
    private javax.swing.JLabel update_type;
    private javax.swing.JLabel updatecase_button;
    // End of variables declaration//GEN-END:variables
}
