package fys;

import java.awt.HeadlessException;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import org.apache.pdfbox.util.PDFMergerUtility;

public class SerDesEmp_UpdateCase extends javax.swing.JPanel {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    boolean isSelected = false;

    public SerDesEmp_UpdateCase() {
        initComponents();
        Panel_Manual.setVisible(false);
        Panel_Manual.setEnabled(false);
        emptyfield_warning.setVisible(false);
        emptyfield_warning.setEnabled(false);
        Field_EntryDate.setEditable(false);
        Field_ResolvedDate.setEditable(false);

        conn = javaconnect.ConnecrDb();

        FYS.getQueryManager().updateClientTable(Table_Clients);
        FYS.getQueryManager().updateBaggageTable(Table_Baggage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Logo = new javax.swing.JLabel();
        Label_CallManual = new javax.swing.JLabel();
        Button_SearchClient = new javax.swing.JLabel();
        Field_SearchClient = new javax.swing.JTextField();
        ScrollPane_Clients = new javax.swing.JScrollPane();
        Table_Clients = new javax.swing.JTable();
        Field_SearchBaggage = new javax.swing.JTextField();
        Button_SearchBaggage = new javax.swing.JLabel();
        ScrollPane_Baggage = new javax.swing.JScrollPane();
        Table_Baggage = new javax.swing.JTable();
        Label_FlightNumber = new javax.swing.JLabel();
        Label_FirstName = new javax.swing.JLabel();
        Label_LastName = new javax.swing.JLabel();
        Label_EmailAddress = new javax.swing.JLabel();
        Label_PhoneNumber = new javax.swing.JLabel();
        Label_ZipCode = new javax.swing.JLabel();
        Label_Address = new javax.swing.JLabel();
        Label_City = new javax.swing.JLabel();
        Label_Country = new javax.swing.JLabel();
        Label_ShippingZipCode = new javax.swing.JLabel();
        Label_ShippingAddress = new javax.swing.JLabel();
        Label_ShippingCity = new javax.swing.JLabel();
        Label_ShippingCountry = new javax.swing.JLabel();
        Field_FlightNumber = new javax.swing.JTextField();
        Field_FirstName = new javax.swing.JTextField();
        Field_LastName = new javax.swing.JTextField();
        Field_EmailAddress = new javax.swing.JTextField();
        Field_PhoneNumber = new javax.swing.JTextField();
        Field_ZipCode = new javax.swing.JTextField();
        Field_Address = new javax.swing.JTextField();
        Field_City = new javax.swing.JTextField();
        Field_Country = new javax.swing.JTextField();
        Field_ShippingZipCode = new javax.swing.JTextField();
        Field_ShippingAddress = new javax.swing.JTextField();
        Field_ShippingCountry = new javax.swing.JTextField();
        Field_ShippingCity = new javax.swing.JTextField();
        Label_Location = new javax.swing.JLabel();
        Label_Brand = new javax.swing.JLabel();
        Label_Color = new javax.swing.JLabel();
        Label_Weight = new javax.swing.JLabel();
        Label_Description = new javax.swing.JLabel();
        Label_EntryDate = new javax.swing.JLabel();
        Label_RetrievalDate = new javax.swing.JLabel();
        Label_Status = new javax.swing.JLabel();
        Field_Location = new javax.swing.JTextField();
        Field_Brand = new javax.swing.JTextField();
        Field_Color = new javax.swing.JTextField();
        Field_Weight = new javax.swing.JTextField();
        ScrollPane_Description = new javax.swing.JScrollPane();
        Field_Description = new javax.swing.JTextArea();
        Field_EntryDate = new javax.swing.JTextField();
        Field_ResolvedDate = new javax.swing.JTextField();
        ComboBox_Status = new javax.swing.JComboBox();
        Button_Save = new javax.swing.JLabel();
        Button_Reset = new javax.swing.JLabel();
        Tab_NewCase = new javax.swing.JLabel();
        Tab_UpdateCase = new javax.swing.JLabel();
        Tab_AddExtraBaggage = new javax.swing.JLabel();
        Tab_LogOut = new javax.swing.JLabel();
        Button_PDF = new javax.swing.JLabel();
        emptyfield_warning = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        Panel_Manual = new javax.swing.JPanel();
        Label_ManualExit = new javax.swing.JLabel();
        Label_Title = new javax.swing.JLabel();
        Label_Info = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_LogoMouseClicked(evt);
            }
        });
        add(Label_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 60));

        Label_CallManual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_CallManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_CallManualMouseClicked(evt);
            }
        });
        add(Label_CallManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 50, 50));

        Button_SearchClient.setBackground(new java.awt.Color(34, 153, 68));
        Button_SearchClient.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_SearchClient.setForeground(new java.awt.Color(255, 255, 255));
        Button_SearchClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button_SearchClient.setText("Search Client");
        Button_SearchClient.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Button_SearchClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_SearchClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_SearchClient.setOpaque(true);
        Button_SearchClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_SearchClientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button_SearchClientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button_SearchClientMouseExited(evt);
            }
        });
        add(Button_SearchClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 140, 30));

        Field_SearchClient.setForeground(new java.awt.Color(153, 0, 0));
        Field_SearchClient.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Field_SearchClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Field_SearchClientKeyReleased(evt);
            }
        });
        add(Field_SearchClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 300, 30));

        Table_Clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Clients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_ClientsMouseClicked(evt);
            }
        });
        ScrollPane_Clients.setViewportView(Table_Clients);

        add(ScrollPane_Clients, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 450, 180));

        Field_SearchBaggage.setForeground(new java.awt.Color(153, 0, 0));
        Field_SearchBaggage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Field_SearchBaggage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Field_SearchBaggageKeyReleased(evt);
            }
        });
        add(Field_SearchBaggage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 300, 30));

        Button_SearchBaggage.setBackground(new java.awt.Color(34, 153, 68));
        Button_SearchBaggage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_SearchBaggage.setForeground(new java.awt.Color(255, 255, 255));
        Button_SearchBaggage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button_SearchBaggage.setText("Search Baggage");
        Button_SearchBaggage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Button_SearchBaggage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_SearchBaggage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_SearchBaggage.setOpaque(true);
        Button_SearchBaggage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_SearchBaggageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button_SearchBaggageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button_SearchBaggageMouseExited(evt);
            }
        });
        add(Button_SearchBaggage, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 140, 30));

        Table_Baggage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_Baggage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_BaggageMouseClicked(evt);
            }
        });
        ScrollPane_Baggage.setViewportView(Table_Baggage);

        add(ScrollPane_Baggage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 450, 180));

        Label_FlightNumber.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_FlightNumber.setForeground(new java.awt.Color(153, 0, 0));
        Label_FlightNumber.setText("Flightnumber:");
        add(Label_FlightNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, 30));

        Label_FirstName.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_FirstName.setForeground(new java.awt.Color(153, 0, 0));
        Label_FirstName.setText("First Name:");
        add(Label_FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, 30));

        Label_LastName.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_LastName.setForeground(new java.awt.Color(153, 0, 0));
        Label_LastName.setText("Last Name:");
        add(Label_LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, 30));

        Label_EmailAddress.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_EmailAddress.setForeground(new java.awt.Color(153, 0, 0));
        Label_EmailAddress.setText("Email Address:");
        add(Label_EmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, 30));

        Label_PhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_PhoneNumber.setForeground(new java.awt.Color(153, 0, 0));
        Label_PhoneNumber.setText("Phone Number:");
        add(Label_PhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, 30));

        Label_ZipCode.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_ZipCode.setForeground(new java.awt.Color(153, 0, 0));
        Label_ZipCode.setText("Zip Code:");
        add(Label_ZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, 30));

        Label_Address.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_Address.setForeground(new java.awt.Color(153, 0, 0));
        Label_Address.setText("Address:");
        add(Label_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, 30));

        Label_City.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_City.setForeground(new java.awt.Color(153, 0, 0));
        Label_City.setText("City:");
        add(Label_City, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, 30));

        Label_Country.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_Country.setForeground(new java.awt.Color(153, 0, 0));
        Label_Country.setText("Country:");
        add(Label_Country, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, 30));

        Label_ShippingZipCode.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_ShippingZipCode.setForeground(new java.awt.Color(153, 0, 0));
        Label_ShippingZipCode.setText("Shipping Zip Code:");
        add(Label_ShippingZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, 30));

        Label_ShippingAddress.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_ShippingAddress.setForeground(new java.awt.Color(153, 0, 0));
        Label_ShippingAddress.setText("Shipping Address:");
        add(Label_ShippingAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, 30));

        Label_ShippingCity.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_ShippingCity.setForeground(new java.awt.Color(153, 0, 0));
        Label_ShippingCity.setText("Shipping City:");
        add(Label_ShippingCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, -1, 30));

        Label_ShippingCountry.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_ShippingCountry.setForeground(new java.awt.Color(153, 0, 0));
        Label_ShippingCountry.setText("Shipping Country:");
        add(Label_ShippingCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, -1, 30));

        Field_FlightNumber.setForeground(new java.awt.Color(153, 0, 0));
        Field_FlightNumber.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_FlightNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 210, 30));

        Field_FirstName.setForeground(new java.awt.Color(153, 0, 0));
        Field_FirstName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 210, 30));

        Field_LastName.setForeground(new java.awt.Color(153, 0, 0));
        Field_LastName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 210, 30));

        Field_EmailAddress.setForeground(new java.awt.Color(153, 0, 0));
        Field_EmailAddress.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Field_EmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_EmailAddressActionPerformed(evt);
            }
        });
        add(Field_EmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 210, 30));

        Field_PhoneNumber.setForeground(new java.awt.Color(153, 0, 0));
        Field_PhoneNumber.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_PhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 210, 30));

        Field_ZipCode.setForeground(new java.awt.Color(153, 0, 0));
        Field_ZipCode.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_ZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 210, 30));

        Field_Address.setForeground(new java.awt.Color(153, 0, 0));
        Field_Address.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 210, 30));

        Field_City.setForeground(new java.awt.Color(153, 0, 0));
        Field_City.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_City, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 210, 30));

        Field_Country.setForeground(new java.awt.Color(153, 0, 0));
        Field_Country.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_Country, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 210, 30));

        Field_ShippingZipCode.setForeground(new java.awt.Color(153, 0, 0));
        Field_ShippingZipCode.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_ShippingZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 210, 30));

        Field_ShippingAddress.setForeground(new java.awt.Color(153, 0, 0));
        Field_ShippingAddress.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_ShippingAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 210, 30));

        Field_ShippingCountry.setForeground(new java.awt.Color(153, 0, 0));
        Field_ShippingCountry.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Field_ShippingCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_ShippingCountryActionPerformed(evt);
            }
        });
        add(Field_ShippingCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 210, 30));

        Field_ShippingCity.setForeground(new java.awt.Color(153, 0, 0));
        Field_ShippingCity.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Field_ShippingCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_ShippingCityActionPerformed(evt);
            }
        });
        add(Field_ShippingCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 210, 30));

        Label_Location.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_Location.setForeground(new java.awt.Color(153, 0, 0));
        Label_Location.setText("Location:");
        add(Label_Location, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, -1, 30));

        Label_Brand.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_Brand.setForeground(new java.awt.Color(153, 0, 0));
        Label_Brand.setText("Brand:");
        add(Label_Brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, -1, 30));

        Label_Color.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_Color.setForeground(new java.awt.Color(153, 0, 0));
        Label_Color.setText("Color:");
        add(Label_Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, -1, 30));

        Label_Weight.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_Weight.setForeground(new java.awt.Color(153, 0, 0));
        Label_Weight.setText("Weight:");
        add(Label_Weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, -1, 30));

        Label_Description.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_Description.setForeground(new java.awt.Color(153, 0, 0));
        Label_Description.setText("Description:");
        add(Label_Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 280, -1, 30));

        Label_EntryDate.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_EntryDate.setForeground(new java.awt.Color(153, 0, 0));
        Label_EntryDate.setText("Entry Date:");
        add(Label_EntryDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 390, 140, 30));

        Label_RetrievalDate.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_RetrievalDate.setForeground(new java.awt.Color(153, 0, 0));
        Label_RetrievalDate.setText("Resolved Date:");
        add(Label_RetrievalDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, 140, 30));

        Label_Status.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Label_Status.setForeground(new java.awt.Color(153, 0, 0));
        Label_Status.setText("Status:");
        add(Label_Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, 140, 30));

        Field_Location.setForeground(new java.awt.Color(153, 0, 0));
        Field_Location.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_Location, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, 230, 30));

        Field_Brand.setForeground(new java.awt.Color(153, 0, 0));
        Field_Brand.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_Brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 190, 230, 30));

        Field_Color.setForeground(new java.awt.Color(153, 0, 0));
        Field_Color.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 220, 230, 30));

        Field_Weight.setForeground(new java.awt.Color(153, 0, 0));
        Field_Weight.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_Weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 250, 230, 30));

        Field_Description.setColumns(20);
        Field_Description.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Field_Description.setRows(5);
        Field_Description.setBorder(null);
        ScrollPane_Description.setViewportView(Field_Description);

        add(ScrollPane_Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 280, 230, 110));

        Field_EntryDate.setForeground(new java.awt.Color(153, 0, 0));
        Field_EntryDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_EntryDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 390, 230, 30));

        Field_ResolvedDate.setForeground(new java.awt.Color(153, 0, 0));
        Field_ResolvedDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_ResolvedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 420, 230, 30));

        ComboBox_Status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Missing (no baggage)", "Not matched (no client)", "Resolved", "Permanently lost" }));
        add(ComboBox_Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 450, 230, 30));

        Button_Save.setBackground(new java.awt.Color(34, 153, 68));
        Button_Save.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_Save.setForeground(new java.awt.Color(255, 255, 255));
        Button_Save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button_Save.setText("Save");
        Button_Save.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Button_Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Save.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_Save.setOpaque(true);
        Button_Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_SaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button_SaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button_SaveMouseExited(evt);
            }
        });
        add(Button_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 600, 130, 30));

        Button_Reset.setBackground(new java.awt.Color(34, 153, 68));
        Button_Reset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_Reset.setForeground(new java.awt.Color(255, 255, 255));
        Button_Reset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button_Reset.setText("Reset");
        Button_Reset.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Button_Reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Reset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_Reset.setOpaque(true);
        Button_Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_ResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button_ResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button_ResetMouseExited(evt);
            }
        });
        add(Button_Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 600, 130, 30));

        Tab_NewCase.setBackground(new java.awt.Color(156, 0, 0));
        Tab_NewCase.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tab_NewCase.setForeground(new java.awt.Color(255, 255, 255));
        Tab_NewCase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tab_NewCase.setText("New Case");
        Tab_NewCase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_NewCase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_NewCase.setOpaque(true);
        Tab_NewCase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_NewCaseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab_NewCaseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab_NewCaseMouseExited(evt);
            }
        });
        add(Tab_NewCase, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, 40));

        Tab_UpdateCase.setBackground(new java.awt.Color(255, 255, 255));
        Tab_UpdateCase.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tab_UpdateCase.setForeground(new java.awt.Color(156, 0, 0));
        Tab_UpdateCase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tab_UpdateCase.setText("Update Case");
        Tab_UpdateCase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_UpdateCase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_UpdateCase.setOpaque(true);
        Tab_UpdateCase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab_UpdateCaseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab_UpdateCaseMouseExited(evt);
            }
        });
        add(Tab_UpdateCase, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 250, 40));

        Tab_AddExtraBaggage.setBackground(new java.awt.Color(156, 0, 0));
        Tab_AddExtraBaggage.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tab_AddExtraBaggage.setForeground(new java.awt.Color(255, 255, 255));
        Tab_AddExtraBaggage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tab_AddExtraBaggage.setText("Add Extra Baggage");
        Tab_AddExtraBaggage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_AddExtraBaggage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_AddExtraBaggage.setOpaque(true);
        Tab_AddExtraBaggage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_AddExtraBaggageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab_AddExtraBaggageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab_AddExtraBaggageMouseExited(evt);
            }
        });
        add(Tab_AddExtraBaggage, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 250, 40));

        Tab_LogOut.setBackground(new java.awt.Color(156, 0, 0));
        Tab_LogOut.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tab_LogOut.setForeground(new java.awt.Color(255, 255, 255));
        Tab_LogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tab_LogOut.setText("Log Out");
        Tab_LogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_LogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_LogOut.setOpaque(true);
        Tab_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_LogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tab_LogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tab_LogOutMouseExited(evt);
            }
        });
        add(Tab_LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 250, 40));

        Button_PDF.setBackground(new java.awt.Color(34, 153, 68));
        Button_PDF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_PDF.setForeground(new java.awt.Color(255, 255, 255));
        Button_PDF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button_PDF.setText("Make PDF");
        Button_PDF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Button_PDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_PDF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_PDF.setOpaque(true);
        Button_PDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_PDFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button_PDFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button_PDFMouseExited(evt);
            }
        });
        add(Button_PDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 600, 130, 30));

        emptyfield_warning.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emptyfield_warning.setForeground(new java.awt.Color(153, 0, 0));
        emptyfield_warning.setText("* One or more required fields are empty. Please fill them in and try again.");
        add(emptyfield_warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, -1, -1));

        Background.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Background.setForeground(new java.awt.Color(153, 0, 0));
        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fys/Images/Background.png"))); // NOI18N
        Background.setOpaque(true);
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1280, 780));

        Panel_Manual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel_Manual.setEnabled(false);
        Panel_Manual.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_ManualExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_ManualExit.setText("X");
        Label_ManualExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_ManualExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_ManualExitMouseClicked(evt);
            }
        });
        Panel_Manual.add(Label_ManualExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 20, 20));

        Label_Title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Title.setForeground(new java.awt.Color(153, 0, 0));
        Label_Title.setText("Manual");
        Panel_Manual.add(Label_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));

        Label_Info.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_Info.setForeground(new java.awt.Color(153, 0, 0));
        Label_Info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Info.setText("<html>\nOn the left side of the screen, fill in the search term\nfor the case you wish to update. This will generate\na list of cases that match your search in the table below. \nClick on the desired table to fill the list of fields to the right.\nFrom here you can change or delete the case's data. If you \nwish to start over, click the 'Reset' button to return the\nfields to their original values. If you're satisfied with the\nchanges you've made, click the 'Save' button to make\nthem permanent.\n<br>\n<br>\nRequired fields are marked by a *.");
        Label_Info.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Panel_Manual.add(Label_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 420));

        add(Panel_Manual, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 290, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void Tab_AddExtraBaggageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_AddExtraBaggageMouseEntered
        Tab_AddExtraBaggage.setBackground(new java.awt.Color(255, 255, 255));
        Tab_AddExtraBaggage.setForeground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_Tab_AddExtraBaggageMouseEntered

    private void Tab_AddExtraBaggageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_AddExtraBaggageMouseExited
        Tab_AddExtraBaggage.setBackground(new java.awt.Color(153, 0, 0));
        Tab_AddExtraBaggage.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Tab_AddExtraBaggageMouseExited


    private void Button_ResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ResetMouseEntered
        Button_Reset.setBackground(new java.awt.Color(51, 136, 68));
    }//GEN-LAST:event_Button_ResetMouseEntered

    private void Button_ResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ResetMouseExited
        Button_Reset.setBackground(new java.awt.Color(34, 153, 68));
    }//GEN-LAST:event_Button_ResetMouseExited

    private void Button_SaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SaveMouseEntered
        Button_Save.setBackground(new java.awt.Color(51, 136, 68));
    }//GEN-LAST:event_Button_SaveMouseEntered

    private void Button_SaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SaveMouseExited
        Button_Save.setBackground(new java.awt.Color(34, 153, 68));
    }//GEN-LAST:event_Button_SaveMouseExited

    private void Tab_LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_LogOutMouseClicked
        FYS.getInstance().showPage(new SerDesEmp_LogOut());
    }//GEN-LAST:event_Tab_LogOutMouseClicked

    private void Tab_LogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_LogOutMouseEntered
        Tab_LogOut.setBackground(new java.awt.Color(255, 255, 255));
        Tab_LogOut.setForeground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_Tab_LogOutMouseEntered

    private void Tab_LogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_LogOutMouseExited
        Tab_LogOut.setBackground(new java.awt.Color(153, 0, 0));
        Tab_LogOut.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Tab_LogOutMouseExited

    private void Tab_NewCaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_NewCaseMouseClicked
        FYS.getInstance().showPage(new SerDesEmp_NewCase());
    }//GEN-LAST:event_Tab_NewCaseMouseClicked

    private void Tab_NewCaseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_NewCaseMouseEntered
        Tab_NewCase.setBackground(new java.awt.Color(255, 255, 255));
        Tab_NewCase.setForeground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_Tab_NewCaseMouseEntered

    private void Tab_NewCaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_NewCaseMouseExited
        Tab_NewCase.setBackground(new java.awt.Color(153, 0, 0));
        Tab_NewCase.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Tab_NewCaseMouseExited

    private void Tab_UpdateCaseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_UpdateCaseMouseEntered

    }//GEN-LAST:event_Tab_UpdateCaseMouseEntered

    private void Tab_UpdateCaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_UpdateCaseMouseExited

    }//GEN-LAST:event_Tab_UpdateCaseMouseExited

    private void Field_SearchClientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Field_SearchClientKeyReleased

    }//GEN-LAST:event_Field_SearchClientKeyReleased

    private void Tab_AddExtraBaggageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_AddExtraBaggageMouseClicked
        FYS.getInstance().showPage(new SerDesEmp_AddBagage());
        Tab_AddExtraBaggage.setForeground(new java.awt.Color(153, 0, 0));
        Tab_AddExtraBaggage.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_Tab_AddExtraBaggageMouseClicked

    /* THESE PROTECTED FIELDS SUCK WHEN NETBEANS FAILS TO RENAME STUFF AND DECIDES TO SCREW EVERYTHING
    private void Label_ManualExitMouseClicked(java.awt.event.MouseEvent evt) {             Panel_Manual//GEN-FIRST:event_Label_ManualExitMouseClicked
        Panel_Manual.setVisible(false);
     Panel_Manual.setEnabled(false);
    }                          Panel_Manual//GEN-LAST:event_Label_ManualExitMouseClicked
*/
    private void Label_ManualExitMouseClicked(java.awt.event.MouseEvent evt) {
        Panel_Manual.setVisible(false);
        Panel_Manual.setEnabled(false);
    }
    /* DUDE FUCKING SERIOUSLY???
    private void LabelPanel_ManualouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_CallManualMouseClicked
        if (Panel_Manual.isVisible()) {
     Panel_Manual.setVisible(false);
     Panel_Manual.setEnabled(false);
     } else {
     Panel_Manual.setVisible(true);
     Panel_Manual.setEnabled(true);

     }
    }//GEN-LAST:event_Label_CallManualMouseClicked
*/

    private void Label_CallManualMouseClicked(java.awt.event.MouseEvent evt) {
        if (Panel_Manual.isVisible()) {
            Panel_Manual.setVisible(false);
            Panel_Manual.setEnabled(false);
        } else {
            Panel_Manual.setVisible(true);
            Panel_Manual.setEnabled(true);
        }
    }

    private void Field_EmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_EmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_EmailAddressActionPerformed

    private void Field_ShippingCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_ShippingCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_ShippingCityActionPerformed

    private void Table_ClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ClientsMouseClicked
        try {
            int row = Table_Clients.getSelectedRow();
            String Table_click = (Table_Clients.getModel().getValueAt(row, 0).toString());

            String sql = "SELECT * FROM client INNER JOIN baggage ON client.clientID = "
                    + "baggage.clientID WHERE client.clientID = '" + Table_click + "'";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {
                Field_FlightNumber.setText(rs.getString("flightNumber"));
                Field_FirstName.setText(rs.getString("firstName"));
                Field_LastName.setText(rs.getString("lastName"));
                Field_EmailAddress.setText(rs.getString("emailAddress"));
                Field_PhoneNumber.setText(rs.getString("phoneNumber"));
                Field_ZipCode.setText(rs.getString("zipCode"));
                Field_Address.setText(rs.getString("address"));
                Field_City.setText(rs.getString("city"));
                Field_Country.setText(rs.getString("country"));
                Field_ShippingZipCode.setText(rs.getString("shippingZipCode"));
                Field_ShippingAddress.setText(rs.getString("shippingAddress"));
                Field_ShippingCity.setText(rs.getString("shippingCity"));
                Field_ShippingCountry.setText(rs.getString("shippingCountry"));

                Field_Location.setText(rs.getString("location"));
                Field_Brand.setText(rs.getString("brand"));
                Field_Color.setText(rs.getString("color"));
                Field_Weight.setText(rs.getString("weight"));
                Field_Description.setText(rs.getString("description"));
                ComboBox_Status.setSelectedIndex(Integer.parseInt(rs.getString("status")));
                Field_EntryDate.setText(rs.getString("startDate"));
                Field_ResolvedDate.setText(rs.getString("resolvedDate"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Table_ClientsMouseClicked

    //TO DO: EVERYTHING HERE, we should use the selected case to make sure the right thing is updated but let me think about that when it's not 4AM
    private void Button_SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SaveMouseClicked
        /*        if (!Check_ClientCase.isSelected() && !Check_BaggageCase.isSelected()) {
         JOptionPane.showMessageDialog(null, "Please select what type of case you wish to make first.");
         } else {
         if (Check_ClientCase.isSelected() && Check_BaggageCase.isSelected()) {
         if ((Field_FlightNumber.getText().equals("") || Field_FirstName.getText().equals("") || Field_LastName.getText().equals("") || Field_ZipCode.getText().equals("") || Field_Address.getText().equals("") || Field_City.getText().equals("") || Field_Country.getText().equals("")) || (Field_Location.getText().equals("") && Field_Brand.getText().equals("") && Field_Color.getText().equals("") && Field_Weight.getText().equals("") && Field_Description.getText().equals(""))) {
         emptyfield_warning.setVisible(true);
         emptyfield_warning.setEnabled(true);
         } else {

         FYS.getQueryManager().updateCase(Field_FlightNumber.getText(), Field_FirstName.getText(), Field_LastName.getText(), Field_EmailAddress.getText(), Field_PhoneNumber.getText(), Field_ZipCode.getText(),
         Field_Address.getText(), Field_City.getText(), Field_Country.getText(), Field_ShippingZipCode.getText(), Field_ShippingAddress.getText(), Field_ShippingCity.getText(), Field_ShippingCountry.getText(),
         Field_Location.getText(), Field_Brand.getText(), Field_Color.getText(), Field_Weight.getText(), Field_Description.getText(), Field_EntryDate.getText(), Field_RetrievalDate.getText(), "" + ComboBox_Status.getSelectedIndex());

         FYS.getQueryManager().updateClientTable(Table_Clients);
         emptyfield_warning.setVisible(false);
         emptyfield_warning.setEnabled(false);
         }
         } else if (Check_ClientCase.isSelected()) {
         if (Field_FlightNumber.getText().equals("") || Field_FirstName.getText().equals("") || Field_LastName.getText().equals("") || Field_ZipCode.getText().equals("") || Field_Address.getText().equals("") || Field_City.getText().equals("") || Field_Country.getText().equals("")) {
         emptyfield_warning.setVisible(true);
         emptyfield_warning.setEnabled(true);
         } else {
                    
         FYS.getQueryManager().updateClientCase(Field_FlightNumber.getText(), Field_FirstName.getText(), Field_LastName.getText(), Field_EmailAddress.getText(), Field_PhoneNumber.getText(), Field_ZipCode.getText(),
         Field_Address.getText(), Field_City.getText(), Field_Country.getText(), Field_ShippingZipCode.getText(), Field_ShippingAddress.getText(), Field_ShippingCity.getText(), Field_ShippingCountry.getText());
                   
         FYS.getQueryManager().updateClientTable(Table_Clients);
         emptyfield_warning.setVisible(false);
         emptyfield_warning.setEnabled(false);
         }

         } else {
         if (Field_Location.getText().equals("") && Field_Brand.getText().equals("") && Field_Color.getText().equals("") && Field_Weight.getText().equals("") && Field_Description.getText().equals("")) {
         emptyfield_warning.setVisible(true);
         emptyfield_warning.setEnabled(true);
         } else {
                    
         FYS.getQueryManager().updateBaggageCase(Field_Location.getText(), Field_Brand.getText(), Field_Color.getText(), Field_Weight.getText(), Field_Description.getText(), Field_EntryDate.getText(), 
         Field_RetrievalDate.getText(), "" + ComboBox_Status.getSelectedIndex());
                    
         FYS.getQueryManager().updateClientTable(Table_Clients);
         emptyfield_warning.setVisible(false);
         emptyfield_warning.setEnabled(false);
         }
         }
         }*/
    }//GEN-LAST:event_Button_SaveMouseClicked

    private void Button_ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ResetMouseClicked
        Field_FirstName.setText("");
        Field_LastName.setText("");
        Field_EmailAddress.setText("");
        Field_PhoneNumber.setText("");
        Field_ZipCode.setText("");
        Field_Address.setText("");
        Field_City.setText("");
        Field_Country.setText("");
        Field_ShippingZipCode.setText("");
        Field_ShippingAddress.setText("");
        Field_ShippingCity.setText("");
        Field_ShippingCountry.setText("");
        Field_Location.setText("");
        Field_Brand.setText("");
        Field_Color.setText("");
        Field_Weight.setText("");
        Field_Description.setText("");
//        Field_EntryDate.setText("");
//        Field_RetrievalDate.setText("");


    }//GEN-LAST:event_Button_ResetMouseClicked

    private void Label_LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_LogoMouseClicked
        FYS.getInstance().showPage(new SerDesEmp_Home());
    }//GEN-LAST:event_Label_LogoMouseClicked

    private void Button_PDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_PDFMouseClicked

        //alles uit het updatecase screen
        int date = 0;
        String firstname = Field_FirstName.getText();
        String lastname = Field_LastName.getText();
        String country = Field_Country.getText();
        String city = Field_City.getText();
        String zipcode = Field_ZipCode.getText();
        String address = Field_Address.getText();
        String phonenumber = Field_PhoneNumber.getText();
        String emailaddress = Field_EmailAddress.getText();
        String shippingcountry = Field_ShippingCountry.getText();
        String shippingzipcode = Field_ShippingZipCode.getText();
        String shippingaddress = Field_ShippingAddress.getText();
        String shippingcity = Field_ShippingCity.getText();
        String flightnumber = Field_ShippingAddress.getText();
        String brand = Field_Brand.getText();
        String color = Field_Color.getText();
        String weight = Field_Weight.getText();
        String description = Field_Description.getText();

        PDFGenerator pdf = new PDFGenerator();
        pdf.generate(date, firstname, lastname, country, city, zipcode, address, phonenumber, emailaddress, shippingcountry, shippingzipcode, shippingaddress, shippingcity, flightnumber, brand, color, weight, description);

        pdf.save(firstname + lastname + zipcode + ".pdf");
        
                

        
        
    }//GEN-LAST:event_Button_PDFMouseClicked

    private void Button_PDFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_PDFMouseEntered
        Button_PDF.setBackground(new java.awt.Color(51, 136, 68));
    }//GEN-LAST:event_Button_PDFMouseEntered

    private void Button_PDFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_PDFMouseExited
        Button_PDF.setBackground(new java.awt.Color(34, 153, 68));
    }//GEN-LAST:event_Button_PDFMouseExited

    private void Field_ShippingCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_ShippingCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_ShippingCountryActionPerformed

    private void Button_SearchClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SearchClientMouseClicked
        try {
            String sql = "select clientID, firstName, lastName from client where clientID=? OR  firstname=? OR lastname=?  ";

            pst = conn.prepareStatement(sql);
            pst.setString(1, Field_SearchClient.getText());
            pst.setString(2, Field_SearchClient.getText());
            pst.setString(3, Field_SearchClient.getText());

            rs = pst.executeQuery();
            Table_Clients.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Button_SearchClientMouseClicked

    private void Button_SearchClientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SearchClientMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_SearchClientMouseEntered

    private void Button_SearchClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SearchClientMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_SearchClientMouseExited

    private void Table_BaggageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_BaggageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Table_BaggageMouseClicked

    private void Field_SearchBaggageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Field_SearchBaggageKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_SearchBaggageKeyReleased

    private void Button_SearchBaggageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SearchBaggageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_SearchBaggageMouseClicked

    private void Button_SearchBaggageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SearchBaggageMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_SearchBaggageMouseEntered

    private void Button_SearchBaggageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SearchBaggageMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_SearchBaggageMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Button_PDF;
    private javax.swing.JLabel Button_Reset;
    private javax.swing.JLabel Button_Save;
    private javax.swing.JLabel Button_SearchBaggage;
    private javax.swing.JLabel Button_SearchClient;
    private javax.swing.JComboBox ComboBox_Status;
    private javax.swing.JTextField Field_Address;
    private javax.swing.JTextField Field_Brand;
    private javax.swing.JTextField Field_City;
    private javax.swing.JTextField Field_Color;
    private javax.swing.JTextField Field_Country;
    private javax.swing.JTextArea Field_Description;
    private javax.swing.JTextField Field_EmailAddress;
    private javax.swing.JTextField Field_EntryDate;
    private javax.swing.JTextField Field_FirstName;
    private javax.swing.JTextField Field_FlightNumber;
    private javax.swing.JTextField Field_LastName;
    private javax.swing.JTextField Field_Location;
    private javax.swing.JTextField Field_PhoneNumber;
    private javax.swing.JTextField Field_ResolvedDate;
    private javax.swing.JTextField Field_SearchBaggage;
    private javax.swing.JTextField Field_SearchClient;
    private javax.swing.JTextField Field_ShippingAddress;
    private javax.swing.JTextField Field_ShippingCity;
    private javax.swing.JTextField Field_ShippingCountry;
    private javax.swing.JTextField Field_ShippingZipCode;
    private javax.swing.JTextField Field_Weight;
    private javax.swing.JTextField Field_ZipCode;
    private javax.swing.JLabel Label_Address;
    private javax.swing.JLabel Label_Brand;
    private javax.swing.JLabel Label_CallManual;
    private javax.swing.JLabel Label_City;
    private javax.swing.JLabel Label_Color;
    private javax.swing.JLabel Label_Country;
    private javax.swing.JLabel Label_Description;
    private javax.swing.JLabel Label_EmailAddress;
    private javax.swing.JLabel Label_EntryDate;
    private javax.swing.JLabel Label_FirstName;
    private javax.swing.JLabel Label_FlightNumber;
    private javax.swing.JLabel Label_Info;
    private javax.swing.JLabel Label_LastName;
    private javax.swing.JLabel Label_Location;
    private javax.swing.JLabel Label_Logo;
    private javax.swing.JLabel Label_ManualExit;
    private javax.swing.JLabel Label_PhoneNumber;
    private javax.swing.JLabel Label_RetrievalDate;
    private javax.swing.JLabel Label_ShippingAddress;
    private javax.swing.JLabel Label_ShippingCity;
    private javax.swing.JLabel Label_ShippingCountry;
    private javax.swing.JLabel Label_ShippingZipCode;
    private javax.swing.JLabel Label_Status;
    private javax.swing.JLabel Label_Title;
    private javax.swing.JLabel Label_Weight;
    private javax.swing.JLabel Label_ZipCode;
    private javax.swing.JPanel Panel_Manual;
    private javax.swing.JScrollPane ScrollPane_Baggage;
    private javax.swing.JScrollPane ScrollPane_Clients;
    private javax.swing.JScrollPane ScrollPane_Description;
    private javax.swing.JLabel Tab_AddExtraBaggage;
    private javax.swing.JLabel Tab_LogOut;
    private javax.swing.JLabel Tab_NewCase;
    private javax.swing.JLabel Tab_UpdateCase;
    private javax.swing.JTable Table_Baggage;
    private javax.swing.JTable Table_Clients;
    private javax.swing.JLabel emptyfield_warning;
    // End of variables declaration//GEN-END:variables
}
