package fys;

import java.awt.HeadlessException;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;

public class SerDesEmp_NewCase extends javax.swing.JPanel {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    public SerDesEmp_NewCase() {
        initComponents();
        conn = javaconnect.ConnecrDb();
        Manual_Panel.setVisible(false);
        Manual_Panel.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employee_id = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        Date_field = new javax.swing.JTextField();
        lname_label = new javax.swing.JLabel();
        lname_field = new javax.swing.JTextField();
        city_label = new javax.swing.JLabel();
        city_field = new javax.swing.JTextField();
        zipcode_label = new javax.swing.JLabel();
        zipcode_field = new javax.swing.JTextField();
        adress_label = new javax.swing.JLabel();
        adress_field = new javax.swing.JTextField();
        phone_label = new javax.swing.JLabel();
        shipcountry_field = new javax.swing.JTextField();
        reset_button = new javax.swing.JLabel();
        save_button = new javax.swing.JLabel();
        shipzipcode_field = new javax.swing.JTextField();
        shippingcountry_label = new javax.swing.JLabel();
        country_label = new javax.swing.JLabel();
        shippingCheckBox = new javax.swing.JCheckBox();
        shippingcity_label = new javax.swing.JLabel();
        shippinzip_label = new javax.swing.JLabel();
        country_field = new javax.swing.JTextField();
        shipaddress_field = new javax.swing.JTextField();
        shippingadress_label = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        phone_field = new javax.swing.JTextField();
        newcase_button = new javax.swing.JLabel();
        addbagage_button = new javax.swing.JLabel();
        updatecase_button = new javax.swing.JLabel();
        LogOut_button = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        flightnmr_label = new javax.swing.JLabel();
        brand_label = new javax.swing.JLabel();
        color_label = new javax.swing.JLabel();
        weight_label = new javax.swing.JLabel();
        description_label = new javax.swing.JLabel();
        shipcity_field = new javax.swing.JTextField();
        flightnmr_field = new javax.swing.JTextField();
        weight_field = new javax.swing.JTextField();
        description_field = new javax.swing.JTextField();
        color_field = new javax.swing.JTextField();
        brand_field = new javax.swing.JTextField();
        Date_label = new javax.swing.JLabel();
        bagageinfo = new javax.swing.JLabel();
        clientinformation = new javax.swing.JLabel();
        fname_label = new javax.swing.JLabel();
        fname_field = new javax.swing.JTextField();
        Manual_Panel = new javax.swing.JPanel();
        Label_ManualExit = new javax.swing.JLabel();
        Label_Title = new javax.swing.JLabel();
        Label_CallManual = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        employee_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employee_id.setForeground(new java.awt.Color(153, 0, 0));
        employee_id.setText("Client Information:");

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 70));

        Date_field.setForeground(new java.awt.Color(153, 0, 0));
        Date_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Date_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 110, 30));

        lname_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lname_label.setForeground(new java.awt.Color(153, 0, 0));
        lname_label.setText("Last name:");
        add(lname_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        lname_field.setForeground(new java.awt.Color(153, 0, 0));
        lname_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(lname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 230, 30));

        city_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        city_label.setForeground(new java.awt.Color(153, 0, 0));
        city_label.setText("City:");
        add(city_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        city_field.setForeground(new java.awt.Color(153, 0, 0));
        city_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(city_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 230, 30));

        zipcode_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        zipcode_label.setForeground(new java.awt.Color(153, 0, 0));
        zipcode_label.setText("Zip Code:");
        add(zipcode_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        zipcode_field.setForeground(new java.awt.Color(153, 0, 0));
        zipcode_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(zipcode_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 230, 30));

        adress_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        adress_label.setForeground(new java.awt.Color(153, 0, 0));
        adress_label.setText("Address:");
        add(adress_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        adress_field.setForeground(new java.awt.Color(153, 0, 0));
        adress_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(adress_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 230, 30));

        phone_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        phone_label.setForeground(new java.awt.Color(153, 0, 0));
        phone_label.setText("Phone number:");
        add(phone_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        shipcountry_field.setForeground(new java.awt.Color(153, 0, 0));
        shipcountry_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(shipcountry_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 230, 30));

        reset_button.setBackground(new java.awt.Color(34, 153, 68));
        reset_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        reset_button.setForeground(new java.awt.Color(255, 255, 255));
        reset_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reset_button.setText("Reset");
        reset_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reset_button.setOpaque(true);
        reset_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reset_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reset_buttonMouseExited(evt);
            }
        });
        add(reset_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 600, 130, -1));

        save_button.setBackground(new java.awt.Color(34, 153, 68));
        save_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        save_button.setForeground(new java.awt.Color(255, 255, 255));
        save_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save_button.setText("Save");
        save_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save_button.setOpaque(true);
        save_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                save_buttonMouseExited(evt);
            }
        });
        add(save_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 130, -1));

        shipzipcode_field.setForeground(new java.awt.Color(153, 0, 0));
        shipzipcode_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(shipzipcode_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 230, 30));

        shippingcountry_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        shippingcountry_label.setForeground(new java.awt.Color(153, 0, 0));
        shippingcountry_label.setText("Shipping country:");
        add(shippingcountry_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        country_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        country_label.setForeground(new java.awt.Color(153, 0, 0));
        country_label.setText("Country:");
        add(country_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        shippingCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        shippingCheckBox.setForeground(new java.awt.Color(153, 0, 0));
        shippingCheckBox.setText("Shipping adress same as living adress");
        shippingCheckBox.setOpaque(false);
        shippingCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shippingCheckBoxActionPerformed(evt);
            }
        });
        add(shippingCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 330, 40));

        shippingcity_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        shippingcity_label.setForeground(new java.awt.Color(153, 0, 0));
        shippingcity_label.setText("Shipping City:");
        add(shippingcity_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, -1));

        shippinzip_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        shippinzip_label.setForeground(new java.awt.Color(153, 0, 0));
        shippinzip_label.setText("Shipping Zip Code:");
        add(shippinzip_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        country_field.setForeground(new java.awt.Color(153, 0, 0));
        country_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(country_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 230, 30));

        shipaddress_field.setForeground(new java.awt.Color(153, 0, 0));
        shipaddress_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(shipaddress_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 230, 30));

        shippingadress_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        shippingadress_label.setForeground(new java.awt.Color(153, 0, 0));
        shippingadress_label.setText("Shipping Address:");
        add(shippingadress_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        email_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        email_label.setForeground(new java.awt.Color(153, 0, 0));
        email_label.setText("E-mail address:");
        add(email_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));

        phone_field.setForeground(new java.awt.Color(153, 0, 0));
        phone_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(phone_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 230, 30));

        newcase_button.setBackground(new java.awt.Color(255, 255, 255));
        newcase_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newcase_button.setForeground(new java.awt.Color(156, 10, 13));
        newcase_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newcase_button.setText("New Case");
        newcase_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newcase_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newcase_button.setOpaque(true);
        newcase_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newcase_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newcase_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newcase_buttonMouseExited(evt);
            }
        });
        add(newcase_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 40));

        addbagage_button.setBackground(new java.awt.Color(156, 0, 0));
        addbagage_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addbagage_button.setForeground(new java.awt.Color(255, 255, 255));
        addbagage_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addbagage_button.setText("Add Bagage");
        addbagage_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbagage_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addbagage_button.setOpaque(true);
        addbagage_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbagage_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addbagage_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addbagage_buttonMouseExited(evt);
            }
        });
        add(addbagage_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 250, 40));

        updatecase_button.setBackground(new java.awt.Color(156, 0, 0));
        updatecase_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        updatecase_button.setForeground(new java.awt.Color(255, 255, 255));
        updatecase_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatecase_button.setText("Update Case");
        updatecase_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatecase_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updatecase_button.setOpaque(true);
        updatecase_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatecase_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updatecase_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updatecase_buttonMouseExited(evt);
            }
        });
        add(updatecase_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 250, 40));

        LogOut_button.setBackground(new java.awt.Color(156, 10, 13));
        LogOut_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LogOut_button.setForeground(new java.awt.Color(255, 255, 255));
        LogOut_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOut_button.setText("Log Out");
        LogOut_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogOut_button.setOpaque(true);
        LogOut_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOut_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOut_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOut_buttonMouseExited(evt);
            }
        });
        add(LogOut_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 250, 40));

        email_field.setForeground(new java.awt.Color(153, 0, 0));
        email_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fieldActionPerformed(evt);
            }
        });
        add(email_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 230, 30));

        flightnmr_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        flightnmr_label.setForeground(new java.awt.Color(153, 0, 0));
        flightnmr_label.setText("Flight number:");
        add(flightnmr_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, -1, -1));

        brand_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        brand_label.setForeground(new java.awt.Color(153, 0, 0));
        brand_label.setText("Brand:");
        add(brand_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, -1, -1));

        color_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        color_label.setForeground(new java.awt.Color(153, 0, 0));
        color_label.setText("Color:");
        add(color_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, -1, -1));

        weight_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        weight_label.setForeground(new java.awt.Color(153, 0, 0));
        weight_label.setText("Weight:");
        add(weight_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 400, -1, -1));

        description_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        description_label.setForeground(new java.awt.Color(153, 0, 0));
        description_label.setText("Description:");
        add(description_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, -1, -1));

        shipcity_field.setForeground(new java.awt.Color(153, 0, 0));
        shipcity_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        shipcity_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipcity_fieldActionPerformed(evt);
            }
        });
        add(shipcity_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 230, 30));

        flightnmr_field.setForeground(new java.awt.Color(153, 0, 0));
        flightnmr_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(flightnmr_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 280, 230, 30));

        weight_field.setForeground(new java.awt.Color(153, 0, 0));
        weight_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(weight_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, 230, 30));

        description_field.setForeground(new java.awt.Color(153, 0, 0));
        description_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(description_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 440, 230, 80));

        color_field.setForeground(new java.awt.Color(153, 0, 0));
        color_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(color_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 360, 230, 30));

        brand_field.setForeground(new java.awt.Color(153, 0, 0));
        brand_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(brand_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 320, 230, 30));

        Date_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Date_label.setForeground(new java.awt.Color(153, 0, 0));
        Date_label.setText("Date:");
        add(Date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        bagageinfo.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        bagageinfo.setForeground(new java.awt.Color(153, 0, 0));
        bagageinfo.setText("Bagage Information:");
        add(bagageinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, -1, -1));

        clientinformation.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        clientinformation.setForeground(new java.awt.Color(153, 0, 0));
        clientinformation.setText("Client Information:");
        add(clientinformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        fname_label.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        fname_label.setForeground(new java.awt.Color(153, 0, 0));
        fname_label.setText("First name:");
        add(fname_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        fname_field.setForeground(new java.awt.Color(153, 0, 0));
        fname_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(fname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 230, 30));

        Manual_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Manual_Panel.setEnabled(false);
        Manual_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_ManualExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_ManualExit.setText("X");
        Label_ManualExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_ManualExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_ManualExitMouseClicked(evt);
            }
        });
        Manual_Panel.add(Label_ManualExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 20, 20));

        Label_Title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Title.setForeground(new java.awt.Color(153, 0, 0));
        Label_Title.setText("Manual");
        Manual_Panel.add(Label_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));

        add(Manual_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 80, 290, 590));

        Label_CallManual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_CallManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_CallManualMouseClicked(evt);
            }
        });
        add(Label_CallManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 50, 50));

        Background.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Background.setForeground(new java.awt.Color(153, 0, 0));
        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fys/Images/Background.png"))); // NOI18N
        Background.setOpaque(true);
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1280, 780));
    }// </editor-fold>//GEN-END:initComponents


    private void reset_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_buttonMouseEntered
        reset_button.setBackground(new java.awt.Color(51, 136, 68));
    }//GEN-LAST:event_reset_buttonMouseEntered

    private void reset_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_buttonMouseExited
        reset_button.setBackground(new java.awt.Color(34, 153, 68));
    }//GEN-LAST:event_reset_buttonMouseExited

    private void save_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseEntered
        save_button.setBackground(new java.awt.Color(51, 136, 68));

    }//GEN-LAST:event_save_buttonMouseEntered

    private void save_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseExited
        save_button.setBackground(new java.awt.Color(34, 153, 68));

    }//GEN-LAST:event_save_buttonMouseExited

    private void shippingCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shippingCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shippingCheckBoxActionPerformed

    private void save_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseClicked
        
       
        try {

            String sql = "insert into client (name,lastname,country,city,zipcode,address,phonenumber,email,shippingcountry,shippingzipcode,shippingaddress,shippingcity)value(?,?,?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);

            pst.setString(1, fname_field.getText());
            pst.setString(2, lname_field.getText());
            pst.setString(3, country_field.getText());
            pst.setString(4, city_field.getText());
            pst.setString(5, zipcode_field.getText());
            pst.setString(6, adress_field.getText());
            pst.setString(7, phone_field.getText());
            pst.setString(8, email_field.getText());
            pst.setString(9, shipcountry_field.getText());
            pst.setString(10, shipzipcode_field.getText());
            pst.setString(11, shipaddress_field.getText());
            pst.setString(12, shipcity_field.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "Saved");

        } catch (SQLException | HeadlessException e) {

            JOptionPane.showMessageDialog(null, e);
        }
       
    
                
    }//GEN-LAST:event_save_buttonMouseClicked

    
    
    private void reset_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_buttonMouseClicked

        Date_field.setText("");
        lname_field.setText("");
        city_field.setText("");
        zipcode_field.setText("");
        adress_field.setText("");
        phone_field.setText("");
        email_field.setText("");
        shipcountry_field.setText("");
        shipzipcode_field.setText("");
        shipaddress_field.setText("");
        shipcity_field.setText("");
        flightnmr_field.setText("");
        brand_field.setText("");
        color_field.setText("");
        weight_field.setText("");
        description_field.setText("");

    }//GEN-LAST:event_reset_buttonMouseClicked

    private void newcase_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newcase_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_newcase_buttonMouseClicked

    private void newcase_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newcase_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_newcase_buttonMouseEntered

    private void newcase_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newcase_buttonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_newcase_buttonMouseExited

    private void addbagage_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbagage_buttonMouseEntered
        addbagage_button.setBackground(new java.awt.Color(255, 255, 255));
        addbagage_button.setForeground(new java.awt.Color(153, 10, 13));
    }//GEN-LAST:event_addbagage_buttonMouseEntered

    private void addbagage_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbagage_buttonMouseExited
        addbagage_button.setBackground(new java.awt.Color(153, 10, 13));

        addbagage_button.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_addbagage_buttonMouseExited

    private void LogOut_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_buttonMouseClicked
        FYS.getInstance().showPage(new SerDesEmp_LogOut());
    }//GEN-LAST:event_LogOut_buttonMouseClicked

    private void LogOut_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_buttonMouseEntered
        LogOut_button.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_LogOut_buttonMouseEntered

    private void LogOut_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_buttonMouseExited
        LogOut_button.setBackground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_LogOut_buttonMouseExited

    private void updatecase_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatecase_buttonMouseEntered
        updatecase_button.setBackground(new java.awt.Color(255, 255, 255));
        updatecase_button.setForeground(new java.awt.Color(153, 10, 13));
    }//GEN-LAST:event_updatecase_buttonMouseEntered

    private void updatecase_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatecase_buttonMouseExited
        addbagage_button.setBackground(new java.awt.Color(153, 10, 13));

        addbagage_button.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_updatecase_buttonMouseExited

    private void email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fieldActionPerformed

    private void shipcity_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipcity_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shipcity_fieldActionPerformed

    private void updatecase_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatecase_buttonMouseClicked
        FYS.getInstance().showPage(new SerDesEmp_UpdateCase());
    }//GEN-LAST:event_updatecase_buttonMouseClicked

    private void addbagage_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbagage_buttonMouseClicked
         FYS.getInstance().showPage(new SerDesEmp_AddBagage());
    }//GEN-LAST:event_addbagage_buttonMouseClicked

    private void Label_ManualExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_ManualExitMouseClicked
        Manual_Panel.setVisible(false);
        Manual_Panel.setEnabled(false);
    }//GEN-LAST:event_Label_ManualExitMouseClicked

    private void Label_CallManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_CallManualMouseClicked
        Manual_Panel.setVisible(true);
        Manual_Panel.setEnabled(true);
    }//GEN-LAST:event_Label_CallManualMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField Date_field;
    private javax.swing.JLabel Date_label;
    private javax.swing.JLabel Label_CallManual;
    private javax.swing.JLabel Label_ManualExit;
    private javax.swing.JLabel Label_Title;
    private javax.swing.JLabel LogOut_button;
    private javax.swing.JPanel Manual_Panel;
    private javax.swing.JLabel addbagage_button;
    private javax.swing.JTextField adress_field;
    private javax.swing.JLabel adress_label;
    private javax.swing.JLabel bagageinfo;
    private javax.swing.JTextField brand_field;
    private javax.swing.JLabel brand_label;
    private javax.swing.JTextField city_field;
    private javax.swing.JLabel city_label;
    private javax.swing.JLabel clientinformation;
    private javax.swing.JTextField color_field;
    private javax.swing.JLabel color_label;
    private javax.swing.JTextField country_field;
    private javax.swing.JLabel country_label;
    private javax.swing.JTextField description_field;
    private javax.swing.JLabel description_label;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel employee_id;
    private javax.swing.JTextField flightnmr_field;
    private javax.swing.JLabel flightnmr_label;
    private javax.swing.JTextField fname_field;
    private javax.swing.JLabel fname_label;
    private javax.swing.JTextField lname_field;
    private javax.swing.JLabel lname_label;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel newcase_button;
    private javax.swing.JTextField phone_field;
    private javax.swing.JLabel phone_label;
    private javax.swing.JLabel reset_button;
    private javax.swing.JLabel save_button;
    private javax.swing.JTextField shipaddress_field;
    private javax.swing.JTextField shipcity_field;
    private javax.swing.JTextField shipcountry_field;
    private javax.swing.JCheckBox shippingCheckBox;
    private javax.swing.JLabel shippingadress_label;
    private javax.swing.JLabel shippingcity_label;
    private javax.swing.JLabel shippingcountry_label;
    private javax.swing.JLabel shippinzip_label;
    private javax.swing.JTextField shipzipcode_field;
    private javax.swing.JLabel updatecase_button;
    private javax.swing.JTextField weight_field;
    private javax.swing.JLabel weight_label;
    private javax.swing.JTextField zipcode_field;
    private javax.swing.JLabel zipcode_label;
    // End of variables declaration//GEN-END:variables
}
