-- MySQL Script generated by MySQL Workbench
-- 12/09/14 16:14:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fysModel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fysModel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fysModel` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fysModel` ;

-- -----------------------------------------------------
-- Table `fysModel`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fysModel`.`employee` (
  `employeeID` INT NOT NULL AUTO_INCREMENT,
  `firstName` CHAR(45) NOT NULL,
  `lastName` CHAR(45) NOT NULL,
  `username` CHAR(20) NOT NULL,
  `password` CHAR(25) NOT NULL,
  `emailAddress` CHAR(40) NULL,
  `phoneNumber` CHAR(45) NULL,
  `function` CHAR(30) NOT NULL,
  `location` CHAR(40) NOT NULL,
  PRIMARY KEY (`employeeID`),
  UNIQUE INDEX `employeeID_UNIQUE` (`employeeID` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fysModel`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fysModel`.`client` (
  `clientID` INT NOT NULL AUTO_INCREMENT,
  `flightNumber` CHAR(45) NULL,
  `firstName` CHAR(45) NULL,
  `lastName` CHAR(45) NULL,
  `emailAddress` CHAR(45) NULL,
  `phoneNumber` CHAR(45) NULL,
  `zipCode` CHAR(10) NULL,
  `address` CHAR(45) NULL,
  `city` CHAR(30) NULL,
  `country` CHAR(30) NULL,
  `shippingZipCode` CHAR(10) NULL,
  `shippingAddress` CHAR(45) NULL,
  `shippingCity` CHAR(45) NULL,
  `shippingCountry` CHAR(30) NULL,
  PRIMARY KEY (`clientID`),
  UNIQUE INDEX `clientID_UNIQUE` (`clientID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fysModel`.`baggage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fysModel`.`baggage` (
  `baggageID` INT NOT NULL AUTO_INCREMENT,
  `flightNumber` CHAR(45) NULL,
  `brand` CHAR(15) NULL,
  `color` CHAR(15) NULL,
  `weight` CHAR(10) NULL,
  `description` CHAR(500) NULL,
  `status` CHAR(40) NOT NULL COMMENT 'not matched, missing, found, permanently lost',
  `startDate` DATETIME NOT NULL,
  `resolvedDate` DATETIME NULL,
  `clientID` INT NULL,
  PRIMARY KEY (`baggageID`),
  UNIQUE INDEX `baggageID_UNIQUE` (`baggageID` ASC),
  INDEX `verzinzelf1_idx` (`clientID` ASC),
  CONSTRAINT `verzinzelf1`
    FOREIGN KEY (`clientID`)
    REFERENCES `fysModel`.`client` (`clientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fysModel`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fysModel`.`log` (
  `logID` INT NOT NULL AUTO_INCREMENT,
  `employeeID` INT NOT NULL,
  `timestamp` TIMESTAMP(0) NOT NULL,
  `screen` CHAR(45) NOT NULL,
  `action` CHAR(45) NOT NULL,
  `affectedClientID` INT NULL,
  `affectedBaggageID` INT NULL,
  `affectedEmployeeID1` INT NULL,
  PRIMARY KEY (`logID`),
  UNIQUE INDEX `logID_UNIQUE` (`logID` ASC),
  INDEX `verzinzelf2_idx` (`affectedClientID` ASC),
  INDEX `verzinzelf3_idx` (`affectedBaggageID` ASC),
  INDEX `verzinzelf4_idx` (`affectedEmployeeID1` ASC),
  CONSTRAINT `verzinzelf2`
    FOREIGN KEY (`affectedClientID`)
    REFERENCES `fysModel`.`client` (`clientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `verzinzelf3`
    FOREIGN KEY (`affectedBaggageID`)
    REFERENCES `fysModel`.`baggage` (`baggageID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `verzinzelf4`
    FOREIGN KEY (`affectedEmployeeID1`)
    REFERENCES `fysModel`.`employee` (`employeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
