-- MySQL Script generated by MySQL Workbench
-- 12/09/14 16:14:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fys
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fys` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fys` ;

-- -----------------------------------------------------
-- Table `fys`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fys`.`employee` (
  `employeeID` INT NOT NULL AUTO_INCREMENT,
  `firstName` CHAR(63) NOT NULL,
  `lastName` CHAR(63) NOT NULL,
  `username` CHAR(31) NOT NULL,
  `password` CHAR(31) NOT NULL,
  `emailAddress` CHAR(63) NULL,
  `phoneNumber` CHAR(31) NULL,
  `function` CHAR(31) NOT NULL,
  `location` CHAR(63) NOT NULL,
  PRIMARY KEY (`employeeID`),
  UNIQUE INDEX `employeeID_UNIQUE` (`employeeID` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fys`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fys`.`client` (
  `clientID` INT NOT NULL AUTO_INCREMENT,
  `flightNumber` CHAR(31) NULL,
  `firstName` CHAR(63) NULL,
  `lastName` CHAR(63) NULL,
  `emailAddress` CHAR(63) NULL,
  `phoneNumber` CHAR(63) NULL,
  `zipCode` CHAR(15) NULL,
  `address` CHAR(63) NULL,
  `city` CHAR(63) NULL,
  `country` CHAR(63) NULL,
  `shippingZipCode` CHAR(15) NULL,
  `shippingAddress` CHAR(63) NULL,
  `shippingCity` CHAR(63) NULL,
  `shippingCountry` CHAR(63) NULL,
  PRIMARY KEY (`clientID`),
  UNIQUE INDEX `clientID_UNIQUE` (`clientID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fys`.`baggage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fys`.`baggage` (
  `baggageID` INT NOT NULL AUTO_INCREMENT,
  `location` CHAR(63) NULL,
  `brand` CHAR(31) NULL,
  `color` CHAR(15) NULL,
  `weight` CHAR(15) NULL,
  `description` CHAR(255) NULL,
  `status` INT NOT NULL COMMENT '0 = Missing, 1 = Not matched, 2 = Resolved, 3 = Permanently lost',
  `startDate` DATETIME NOT NULL,
  `resolvedDate` DATETIME NULL,
  `clientID` INT NULL,
  PRIMARY KEY (`baggageID`),
  UNIQUE INDEX `baggageID_UNIQUE` (`baggageID` ASC))
--   INDEX `has_owner_idx` (`clientID` ASC),
--   CONSTRAINT `has_owner`
--     FOREIGN KEY (`clientID`)
--     REFERENCES `fys`.`client` (`clientID`)
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fys`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fys`.`log` (
  `username` CHAR(31) NOT NULL,
  `timestamp` TIMESTAMP(0) NOT NULL,
  `page` CHAR(31) NOT NULL,
  `action` CHAR(255) NOT NULL,
  PRIMARY KEY (`username`, `timestamp`)) 
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO employee
(firstName, lastName, username, password, emailAddress, phoneNumber, function, location)
VALUES ('Jan', 'Janssen', 'appmanager1', 'appmanager123', 'jan@corendon.nl', '0612300321', 'application manager', 'Schiphol');

INSERT INTO employee
(firstName, lastName, username, password, emailAddress, phoneNumber, function, location)
VALUES ('Henk', 'de Vries', 'manager1', 'manager123', 'henk@corendon.nl', '0687654321', 'manager', 'Schiphol'); 

INSERT INTO employee
(firstName, lastName, username, password, emailAddress, phoneNumber, function, location)
VALUES ('Evert', 'Smit', 'serdesemp1', 'serdesemp123', 'evert@corendon.nl', '0612344321', 'service desk employee', 'Schiphol');

INSERT INTO client
(flightNumber, firstName, lastName, emailAddress, phoneNumber, zipCode, address, city, country, shippingZipCode, shippingAddress, shippingCity, shippingCountry)
VALUES ('MH18', 'Floris', 'van Lent', 'floris.van.lent@hva.nl', '0613371337', '1337 WC', 'Pindakaaslaan 2', 'Amsterdam', 'Nederland', '1337 WC', 'Pindakaaslaan 2', 'Amsterdam', 'Nederland');

INSERT INTO baggage
(location, brand, color, weight, description, status, startDate, resolvedDate, clientID)
VALUES ('Schiphol', 'Samsonite', 'Blauw', '10 kg', 'Er staat vet groot "FLORIS" op', '2', '2014-08-14 13:37:00', '2014-08-15 13:37:00', '1');