package fys;

import javax.swing.ImageIcon;

public class LogoutStandBy extends javax.swing.JPanel {

    public LogoutStandBy() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        Login_button1 = new javax.swing.JLabel();
        LoginLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Login_button = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 70));

        Login_button1.setBackground(new java.awt.Color(34, 153, 68));
        Login_button1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Login_button1.setForeground(new java.awt.Color(255, 255, 255));
        Login_button1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login_button1.setText("Continue");
        Login_button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login_button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login_button1.setOpaque(true);
        Login_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Login_button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Login_button1MouseExited(evt);
            }
        });
        add(Login_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 130, -1));

        LoginLogo.setBackground(new java.awt.Color(255, 255, 255));
        LoginLogo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LoginLogo.setForeground(new java.awt.Color(153, 0, 0));
        LoginLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginLogo.setText("Stand by");
        LoginLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoginLogo.setOpaque(true);
        add(LoginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Click Continue to Log in");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 390, 140));

        Login_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Login_button.setForeground(new java.awt.Color(153, 0, 0));
        Login_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fys/Images/Background (1).png"))); // NOI18N
        Login_button.setOpaque(true);
        add(Login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1280, 780));
    }// </editor-fold>//GEN-END:initComponents


    private void Login_button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_button1MouseEntered
        Login_button1.setBackground(new java.awt.Color(51, 136, 68));

    }//GEN-LAST:event_Login_button1MouseEntered

    private void Login_button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_button1MouseExited
        Login_button1.setBackground(new java.awt.Color(34, 153, 68));

    }//GEN-LAST:event_Login_button1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginLogo;
    private javax.swing.JLabel Login_button;
    private javax.swing.JLabel Login_button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
