package fys;

import javax.swing.ImageIcon;

public class SerDesEmp_UpdateCase extends javax.swing.JPanel {

    public SerDesEmp_UpdateCase() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        employee_id = new javax.swing.JLabel();
        employeeid_field = new javax.swing.JTextField();
        first_name = new javax.swing.JLabel();
        firstname_field = new javax.swing.JTextField();
        last_name = new javax.swing.JLabel();
        lastname_field = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        password_field = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        ManageAccounts_button = new javax.swing.JLabel();
        reset_button = new javax.swing.JLabel();
        save_button = new javax.swing.JLabel();
        LogOut_button2 = new javax.swing.JLabel();
        newaccount_button4 = new javax.swing.JLabel();
        employee_id3 = new javax.swing.JLabel();
        LogOut_button3 = new javax.swing.JLabel();
        ManageAccounts_button1 = new javax.swing.JLabel();
        email_field2 = new javax.swing.JTextField();
        employee_id1 = new javax.swing.JLabel();
        employeeid_field1 = new javax.swing.JTextField();
        employee_id2 = new javax.swing.JLabel();
        employeeid_field2 = new javax.swing.JTextField();
        email3 = new javax.swing.JLabel();
        email_field3 = new javax.swing.JTextField();
        employee_id4 = new javax.swing.JLabel();
        employeeid_field3 = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 70));

        employee_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employee_id.setForeground(new java.awt.Color(153, 0, 0));
        employee_id.setText("Bagage number");
        add(employee_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        employeeid_field.setForeground(new java.awt.Color(153, 0, 0));
        employeeid_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(employeeid_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 320, 30));

        first_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        first_name.setForeground(new java.awt.Color(153, 0, 0));
        first_name.setText("Brand");
        add(first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        firstname_field.setForeground(new java.awt.Color(153, 0, 0));
        firstname_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(firstname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 320, 30));

        last_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        last_name.setForeground(new java.awt.Color(153, 0, 0));
        last_name.setText("Color");
        add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        lastname_field.setForeground(new java.awt.Color(153, 0, 0));
        lastname_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(lastname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 320, 30));

        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(153, 0, 0));
        username.setText("Height");
        add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        username_field.setForeground(new java.awt.Color(153, 0, 0));
        username_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 320, 30));

        password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(153, 0, 0));
        password.setText("Width");
        add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        password_field.setForeground(new java.awt.Color(153, 0, 0));
        password_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 320, 30));

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(153, 0, 0));
        email.setText("Length");
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        ManageAccounts_button.setBackground(new java.awt.Color(255, 255, 255));
        ManageAccounts_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ManageAccounts_button.setForeground(new java.awt.Color(156, 0, 0));
        ManageAccounts_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageAccounts_button.setText("New Bagage");
        ManageAccounts_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageAccounts_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ManageAccounts_button.setOpaque(true);
        ManageAccounts_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageAccounts_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageAccounts_buttonMouseExited(evt);
            }
        });
        add(ManageAccounts_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 250, 40));

        reset_button.setBackground(new java.awt.Color(34, 153, 68));
        reset_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        reset_button.setForeground(new java.awt.Color(255, 255, 255));
        reset_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reset_button.setText("Reset");
        reset_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reset_button.setOpaque(true);
        reset_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reset_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reset_buttonMouseExited(evt);
            }
        });
        add(reset_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 600, 130, -1));

        save_button.setBackground(new java.awt.Color(34, 153, 68));
        save_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        save_button.setForeground(new java.awt.Color(255, 255, 255));
        save_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save_button.setText("Save");
        save_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save_button.setOpaque(true);
        save_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                save_buttonMouseExited(evt);
            }
        });
        add(save_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 130, -1));

        LogOut_button2.setBackground(new java.awt.Color(156, 10, 13));
        LogOut_button2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LogOut_button2.setForeground(new java.awt.Color(255, 255, 255));
        LogOut_button2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOut_button2.setText("Log Out");
        LogOut_button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut_button2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogOut_button2.setOpaque(true);
        LogOut_button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOut_button2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOut_button2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOut_button2MouseExited(evt);
            }
        });
        add(LogOut_button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 250, 40));

        newaccount_button4.setBackground(new java.awt.Color(156, 0, 0));
        newaccount_button4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newaccount_button4.setForeground(new java.awt.Color(255, 255, 255));
        newaccount_button4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newaccount_button4.setText("New Client");
        newaccount_button4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newaccount_button4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newaccount_button4.setOpaque(true);
        newaccount_button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newaccount_button4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newaccount_button4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newaccount_button4MouseExited(evt);
            }
        });
        add(newaccount_button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 40));

        employee_id3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employee_id3.setForeground(new java.awt.Color(153, 0, 0));
        employee_id3.setText("Bagage information");
        add(employee_id3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        LogOut_button3.setBackground(new java.awt.Color(156, 10, 13));
        LogOut_button3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LogOut_button3.setForeground(new java.awt.Color(255, 255, 255));
        LogOut_button3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOut_button3.setText("Search");
        LogOut_button3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut_button3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogOut_button3.setOpaque(true);
        LogOut_button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOut_button3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOut_button3MouseExited(evt);
            }
        });
        add(LogOut_button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 250, 40));

        ManageAccounts_button1.setBackground(new java.awt.Color(156, 10, 13));
        ManageAccounts_button1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ManageAccounts_button1.setForeground(new java.awt.Color(255, 255, 255));
        ManageAccounts_button1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageAccounts_button1.setText("Manage Cases");
        ManageAccounts_button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageAccounts_button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ManageAccounts_button1.setOpaque(true);
        ManageAccounts_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageAccounts_button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageAccounts_button1MouseExited(evt);
            }
        });
        add(ManageAccounts_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 250, 40));

        email_field2.setForeground(new java.awt.Color(153, 0, 0));
        email_field2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(email_field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 320, 30));

        employee_id1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employee_id1.setForeground(new java.awt.Color(153, 0, 0));
        employee_id1.setText("Description");
        add(employee_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, -1, -1));

        employeeid_field1.setForeground(new java.awt.Color(153, 0, 0));
        employeeid_field1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(employeeid_field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, 320, 170));

        employee_id2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employee_id2.setForeground(new java.awt.Color(153, 0, 0));
        employee_id2.setText("Client Number");
        add(employee_id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        employeeid_field2.setForeground(new java.awt.Color(153, 0, 0));
        employeeid_field2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(employeeid_field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 320, 30));

        email3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email3.setForeground(new java.awt.Color(153, 0, 0));
        email3.setText("Weight");
        add(email3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));

        email_field3.setForeground(new java.awt.Color(153, 0, 0));
        email_field3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(email_field3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 320, 30));

        employee_id4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employee_id4.setForeground(new java.awt.Color(153, 0, 0));
        employee_id4.setText("Flight number");
        add(employee_id4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        employeeid_field3.setForeground(new java.awt.Color(153, 0, 0));
        employeeid_field3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(employeeid_field3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 320, 30));

        Background.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Background.setForeground(new java.awt.Color(153, 0, 0));
        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fys/Images/Background.png"))); // NOI18N
        Background.setOpaque(true);
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1280, 780));
    }// </editor-fold>//GEN-END:initComponents

    private void ManageAccounts_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageAccounts_buttonMouseEntered
        ManageAccounts_button.setBackground(new java.awt.Color(255, 255, 255));
        ManageAccounts_button.setForeground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_ManageAccounts_buttonMouseEntered

    private void ManageAccounts_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageAccounts_buttonMouseExited
        ManageAccounts_button.setBackground(new java.awt.Color(153, 0, 0));

        ManageAccounts_button.setForeground(new java.awt.Color(255, 255, 255));

    }//GEN-LAST:event_ManageAccounts_buttonMouseExited


    private void reset_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_buttonMouseEntered
        reset_button.setBackground(new java.awt.Color(51, 136, 68));
    }//GEN-LAST:event_reset_buttonMouseEntered

    private void reset_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_buttonMouseExited
        reset_button.setBackground(new java.awt.Color(34, 153, 68));
    }//GEN-LAST:event_reset_buttonMouseExited

    private void save_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseEntered
        save_button.setBackground(new java.awt.Color(51, 136, 68));

    }//GEN-LAST:event_save_buttonMouseEntered

    private void save_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseExited
        save_button.setBackground(new java.awt.Color(34, 153, 68));

    }//GEN-LAST:event_save_buttonMouseExited

    private void newaccount_button4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newaccount_button4MouseEntered
    }//GEN-LAST:event_newaccount_button4MouseEntered

    private void newaccount_button4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newaccount_button4MouseExited

     }//GEN-LAST:event_newaccount_button4MouseExited

    private void LogOut_button3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_button3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOut_button3MouseEntered

    private void LogOut_button3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_button3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOut_button3MouseExited

    private void ManageAccounts_button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageAccounts_button1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageAccounts_button1MouseEntered

    private void ManageAccounts_button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageAccounts_button1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageAccounts_button1MouseExited

    private void LogOut_button2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_button2MouseExited
        LogOut_button2.setBackground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_LogOut_button2MouseExited

    private void LogOut_button2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_button2MouseEntered
        LogOut_button2.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_LogOut_button2MouseEntered

    private void newaccount_button4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newaccount_button4MouseClicked
        FYS.getInstance().showPage(new SerDesEmp_NewCase());
    }//GEN-LAST:event_newaccount_button4MouseClicked

    private void LogOut_button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_button2MouseClicked
        FYS.getInstance().showPage(new SerDesEmp_LogOut());
    }//GEN-LAST:event_LogOut_button2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel LogOut_button2;
    private javax.swing.JLabel LogOut_button3;
    private javax.swing.JLabel ManageAccounts_button;
    private javax.swing.JLabel ManageAccounts_button1;
    private javax.swing.JLabel email;
    private javax.swing.JLabel email3;
    private javax.swing.JTextField email_field2;
    private javax.swing.JTextField email_field3;
    private javax.swing.JLabel employee_id;
    private javax.swing.JLabel employee_id1;
    private javax.swing.JLabel employee_id2;
    private javax.swing.JLabel employee_id3;
    private javax.swing.JLabel employee_id4;
    private javax.swing.JTextField employeeid_field;
    private javax.swing.JTextField employeeid_field1;
    private javax.swing.JTextField employeeid_field2;
    private javax.swing.JTextField employeeid_field3;
    private javax.swing.JLabel first_name;
    private javax.swing.JTextField firstname_field;
    private javax.swing.JLabel last_name;
    private javax.swing.JTextField lastname_field;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel newaccount_button4;
    private javax.swing.JLabel password;
    private javax.swing.JTextField password_field;
    private javax.swing.JLabel reset_button;
    private javax.swing.JLabel save_button;
    private javax.swing.JLabel username;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables
}
