package fys;

import javax.swing.ImageIcon;

public class AppMan_ManageAccount extends javax.swing.JPanel {

    public AppMan_ManageAccount() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        account_type = new javax.swing.JLabel();
        servicedeskworker_radiobutton = new javax.swing.JRadioButton();
        servicedeskworker_radiobutton1 = new javax.swing.JRadioButton();
        servicedeskworker_radiobutton2 = new javax.swing.JRadioButton();
        employee_id = new javax.swing.JLabel();
        employeeid_field = new javax.swing.JTextField();
        first_name = new javax.swing.JLabel();
        firstname_field = new javax.swing.JTextField();
        last_name = new javax.swing.JLabel();
        lastname_field = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        password_field = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        phone_number = new javax.swing.JLabel();
        phonenumber_field = new javax.swing.JTextField();
        ManageAccounts_button = new javax.swing.JLabel();
        save_button = new javax.swing.JLabel();
        save_button1 = new javax.swing.JLabel();
        RemoteShutdown_button1 = new javax.swing.JLabel();
        LogOut_button2 = new javax.swing.JLabel();
        newaccount_button4 = new javax.swing.JLabel();
        Reset_button = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 70));

        account_type.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        account_type.setForeground(new java.awt.Color(153, 0, 0));
        account_type.setText("Account Type:");
        add(account_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        servicedeskworker_radiobutton.setBackground(new java.awt.Color(255, 255, 255));
        servicedeskworker_radiobutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        servicedeskworker_radiobutton.setForeground(new java.awt.Color(153, 0, 0));
        servicedeskworker_radiobutton.setText("Service Desk Worker");
        servicedeskworker_radiobutton.setBorder(null);
        servicedeskworker_radiobutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        servicedeskworker_radiobutton.setOpaque(false);
        add(servicedeskworker_radiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        servicedeskworker_radiobutton1.setBackground(new java.awt.Color(255, 255, 255));
        servicedeskworker_radiobutton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        servicedeskworker_radiobutton1.setForeground(new java.awt.Color(153, 0, 0));
        servicedeskworker_radiobutton1.setText("Application Manager");
        servicedeskworker_radiobutton1.setBorder(null);
        servicedeskworker_radiobutton1.setOpaque(false);
        servicedeskworker_radiobutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicedeskworker_radiobutton1ActionPerformed(evt);
            }
        });
        add(servicedeskworker_radiobutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, -1, -1));

        servicedeskworker_radiobutton2.setBackground(new java.awt.Color(255, 255, 255));
        servicedeskworker_radiobutton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        servicedeskworker_radiobutton2.setForeground(new java.awt.Color(153, 0, 0));
        servicedeskworker_radiobutton2.setText("Manager");
        servicedeskworker_radiobutton2.setBorder(null);
        servicedeskworker_radiobutton2.setOpaque(false);
        add(servicedeskworker_radiobutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, -1, -1));

        employee_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employee_id.setForeground(new java.awt.Color(153, 0, 0));
        employee_id.setText("Employee ID:");
        add(employee_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        employeeid_field.setForeground(new java.awt.Color(153, 0, 0));
        employeeid_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(employeeid_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 520, 30));

        first_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        first_name.setForeground(new java.awt.Color(153, 0, 0));
        first_name.setText("First Name:");
        add(first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        firstname_field.setForeground(new java.awt.Color(153, 0, 0));
        firstname_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(firstname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 520, 30));

        last_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        last_name.setForeground(new java.awt.Color(153, 0, 0));
        last_name.setText("Last Name:");
        add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        lastname_field.setForeground(new java.awt.Color(153, 0, 0));
        lastname_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(lastname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 520, 30));

        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(153, 0, 0));
        username.setText("Username:");
        add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        username_field.setForeground(new java.awt.Color(153, 0, 0));
        username_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 520, 30));

        password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(153, 0, 0));
        password.setText("Password:");
        add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        password_field.setForeground(new java.awt.Color(153, 0, 0));
        password_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 520, 30));

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(153, 0, 0));
        email.setText("Email:");
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, -1, -1));

        email_field.setForeground(new java.awt.Color(153, 0, 0));
        email_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(email_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 520, 30));

        phone_number.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phone_number.setForeground(new java.awt.Color(153, 0, 0));
        phone_number.setText("Phone Number:");
        add(phone_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, -1, -1));

        phonenumber_field.setForeground(new java.awt.Color(153, 0, 0));
        phonenumber_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(phonenumber_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 520, 30));

        ManageAccounts_button.setBackground(new java.awt.Color(156, 10, 13));
        ManageAccounts_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ManageAccounts_button.setForeground(new java.awt.Color(255, 255, 255));
        ManageAccounts_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageAccounts_button.setText("Manage Accounts");
        ManageAccounts_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageAccounts_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ManageAccounts_button.setOpaque(true);
        ManageAccounts_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageAccounts_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageAccounts_buttonMouseExited(evt);
            }
        });
        add(ManageAccounts_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 250, 40));

        save_button.setBackground(new java.awt.Color(34, 153, 68));
        save_button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        save_button.setForeground(new java.awt.Color(255, 255, 255));
        save_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save_button.setText("Reset");
        save_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save_button.setOpaque(true);
        save_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                save_buttonMouseExited(evt);
            }
        });
        add(save_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, 130, -1));

        save_button1.setBackground(new java.awt.Color(34, 153, 68));
        save_button1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        save_button1.setForeground(new java.awt.Color(255, 255, 255));
        save_button1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save_button1.setText("Save");
        save_button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        save_button1.setOpaque(true);
        save_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save_button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                save_button1MouseExited(evt);
            }
        });
        add(save_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 130, -1));

        RemoteShutdown_button1.setBackground(new java.awt.Color(156, 10, 13));
        RemoteShutdown_button1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        RemoteShutdown_button1.setForeground(new java.awt.Color(255, 255, 255));
        RemoteShutdown_button1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RemoteShutdown_button1.setText("Remote Shutdown");
        RemoteShutdown_button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RemoteShutdown_button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RemoteShutdown_button1.setOpaque(true);
        RemoteShutdown_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RemoteShutdown_button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RemoteShutdown_button1MouseExited(evt);
            }
        });
        add(RemoteShutdown_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 250, 40));

        LogOut_button2.setBackground(new java.awt.Color(156, 10, 13));
        LogOut_button2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LogOut_button2.setForeground(new java.awt.Color(255, 255, 255));
        LogOut_button2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOut_button2.setText("Log Out");
        LogOut_button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut_button2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LogOut_button2.setOpaque(true);
        LogOut_button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOut_button2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOut_button2MouseExited(evt);
            }
        });
        add(LogOut_button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 250, 40));

        newaccount_button4.setBackground(new java.awt.Color(255, 255, 255));
        newaccount_button4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newaccount_button4.setForeground(new java.awt.Color(156, 10, 13));
        newaccount_button4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newaccount_button4.setText("New Account");
        newaccount_button4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newaccount_button4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newaccount_button4.setOpaque(true);
        newaccount_button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newaccount_button4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newaccount_button4MouseExited(evt);
            }
        });
        add(newaccount_button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 250, 40));

        Reset_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Reset_button.setForeground(new java.awt.Color(153, 0, 0));
        Reset_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reset_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fys/Images/Background (1).png"))); // NOI18N
        Reset_button.setOpaque(true);
        add(Reset_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1280, 780));
    }// </editor-fold>//GEN-END:initComponents

    private void ManageAccounts_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageAccounts_buttonMouseEntered
        ManageAccounts_button.setBackground(new java.awt.Color(255, 255, 255));
        ManageAccounts_button.setForeground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_ManageAccounts_buttonMouseEntered

    private void ManageAccounts_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageAccounts_buttonMouseExited
        ManageAccounts_button.setBackground(new java.awt.Color(153, 0, 0));

        ManageAccounts_button.setForeground(new java.awt.Color(255, 255, 255));

    }//GEN-LAST:event_ManageAccounts_buttonMouseExited


    private void save_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseEntered
        save_button.setBackground(new java.awt.Color(51, 136, 68));
    }//GEN-LAST:event_save_buttonMouseEntered

    private void save_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseExited
        save_button.setBackground(new java.awt.Color(34, 153, 68));
    }//GEN-LAST:event_save_buttonMouseExited

    private void servicedeskworker_radiobutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicedeskworker_radiobutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servicedeskworker_radiobutton1ActionPerformed

    private void save_button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_button1MouseEntered
        save_button1.setBackground(new java.awt.Color(51, 136, 68));

    }//GEN-LAST:event_save_button1MouseEntered

    private void save_button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_button1MouseExited
        save_button1.setBackground(new java.awt.Color(34, 153, 68));

    }//GEN-LAST:event_save_button1MouseExited

    private void RemoteShutdown_button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoteShutdown_button1MouseEntered
        RemoteShutdown_button1.setBackground(new java.awt.Color(255, 255, 255));
        RemoteShutdown_button1.setForeground(new java.awt.Color(153, 0, 0));    }//GEN-LAST:event_RemoteShutdown_button1MouseEntered

    private void RemoteShutdown_button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoteShutdown_button1MouseExited
        RemoteShutdown_button1.setBackground(new java.awt.Color(153, 0, 0));

        RemoteShutdown_button1.setForeground(new java.awt.Color(255, 255, 255));    }//GEN-LAST:event_RemoteShutdown_button1MouseExited

    private void LogOut_button2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_button2MouseEntered
        LogOut_button2.setBackground(new java.awt.Color(255, 255, 255));
        LogOut_button2.setForeground(new java.awt.Color(153, 0, 0));     }//GEN-LAST:event_LogOut_button2MouseEntered

    private void LogOut_button2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut_button2MouseExited
        LogOut_button2.setBackground(new java.awt.Color(153, 0, 0));

        LogOut_button2.setForeground(new java.awt.Color(255, 255, 255));    }//GEN-LAST:event_LogOut_button2MouseExited

    private void newaccount_button4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newaccount_button4MouseEntered
    }//GEN-LAST:event_newaccount_button4MouseEntered

    private void newaccount_button4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newaccount_button4MouseExited

     }//GEN-LAST:event_newaccount_button4MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogOut_button2;
    private javax.swing.JLabel ManageAccounts_button;
    private javax.swing.JLabel RemoteShutdown_button1;
    private javax.swing.JLabel Reset_button;
    private javax.swing.JLabel account_type;
    private javax.swing.JLabel email;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel employee_id;
    private javax.swing.JTextField employeeid_field;
    private javax.swing.JLabel first_name;
    private javax.swing.JTextField firstname_field;
    private javax.swing.JLabel last_name;
    private javax.swing.JTextField lastname_field;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel newaccount_button4;
    private javax.swing.JLabel password;
    private javax.swing.JTextField password_field;
    private javax.swing.JLabel phone_number;
    private javax.swing.JTextField phonenumber_field;
    private javax.swing.JLabel save_button;
    private javax.swing.JLabel save_button1;
    private javax.swing.JRadioButton servicedeskworker_radiobutton;
    private javax.swing.JRadioButton servicedeskworker_radiobutton1;
    private javax.swing.JRadioButton servicedeskworker_radiobutton2;
    private javax.swing.JLabel username;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables
}
