package fys;

import javax.swing.ImageIcon;

public class Login extends javax.swing.JPanel {

    public Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Username = new javax.swing.JLabel();
        Label_Password = new javax.swing.JLabel();
        Field_Username = new javax.swing.JTextField();
        Field_Password = new javax.swing.JTextField();
        Button_LogIn = new javax.swing.JLabel();
        Tab_LogIn = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_Username.setForeground(new java.awt.Color(153, 0, 0));
        Label_Username.setText("Username:");
        add(Label_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        Label_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_Password.setForeground(new java.awt.Color(153, 0, 0));
        Label_Password.setText("Password:");
        add(Label_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        Field_Username.setForeground(new java.awt.Color(153, 0, 0));
        Field_Username.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 520, 30));

        Field_Password.setForeground(new java.awt.Color(153, 0, 0));
        Field_Password.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(Field_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 520, 30));

        Button_LogIn.setBackground(new java.awt.Color(34, 153, 68));
        Button_LogIn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_LogIn.setForeground(new java.awt.Color(255, 255, 255));
        Button_LogIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button_LogIn.setText("Log In");
        Button_LogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_LogIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_LogIn.setOpaque(true);
        Button_LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button_LogInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button_LogInMouseExited(evt);
            }
        });
        add(Button_LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 130, -1));

        Tab_LogIn.setBackground(new java.awt.Color(255, 255, 255));
        Tab_LogIn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tab_LogIn.setForeground(new java.awt.Color(153, 0, 0));
        Tab_LogIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tab_LogIn.setText("Log In");
        Tab_LogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tab_LogIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Tab_LogIn.setOpaque(true);
        add(Tab_LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, 40));

        Background.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Background.setForeground(new java.awt.Color(153, 0, 0));
        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fys/Images/Background.png"))); // NOI18N
        Background.setOpaque(true);
        add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1280, 780));
    }// </editor-fold>//GEN-END:initComponents


    private void Button_LogInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_LogInMouseEntered
        Button_LogIn.setBackground(new java.awt.Color(51, 136, 68));

    }//GEN-LAST:event_Button_LogInMouseEntered

    private void Button_LogInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_LogInMouseExited
        Button_LogIn.setBackground(new java.awt.Color(34, 153, 68));

    }//GEN-LAST:event_Button_LogInMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Button_LogIn;
    private javax.swing.JTextField Field_Password;
    private javax.swing.JTextField Field_Username;
    private javax.swing.JLabel Label_Password;
    private javax.swing.JLabel Label_Username;
    private javax.swing.JLabel Tab_LogIn;
    // End of variables declaration//GEN-END:variables
}
